[[Clang_assert]]
arch = "aarch64"
git-tree-sha1 = "471df0765dd86806d6931f34477815716fd3b502"
os = "macos"

    [[Clang_assert.download]]
    sha256 = "03f6bbe08f8d802f265feff6db27ca49d6f3b9e0fd01c97ff9b31d5e505acd06"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v11.0.0+4/Clang_assert.v11.0.0.aarch64-apple-darwin.tar.gz"
[[Clang_assert]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9b041beb99fe2a7ab4e3ad7104866fa83849ad2f"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "466198691288e1ea27dad63443b53843520ea16b9ef3ac3c2f26cdec56f04826"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v11.0.0+4/Clang_assert.v11.0.0.aarch64-linux-gnu-cxx03.tar.gz"
[[Clang_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6d1f847928f29191016446e9f22164d0ede5b6b2"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "4c8e17c63f98fc67ff109314a430ed7a06bcc4f89031c4706ba2ea7ef21600f6"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v11.0.0+4/Clang_assert.v11.0.0.aarch64-linux-gnu-cxx11.tar.gz"
[[Clang_assert]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d9b4b7af46e59a0c4af799cfa043ea4f074a3fa8"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "c0c40b27c3affbb1313b9f0bd748e48ee9410cd15fdd947683bc83930f562ab6"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v11.0.0+4/Clang_assert.v11.0.0.aarch64-linux-musl-cxx03.tar.gz"
[[Clang_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8cb847c9c171925278f60a42975ff99bb569a871"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "9f7323d37ea32897aba491241863beb654935ff13f2234133b77704a75a0d2b9"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v11.0.0+4/Clang_assert.v11.0.0.aarch64-linux-musl-cxx11.tar.gz"
[[Clang_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b380f42516c404ee502690401c9ee566286548eb"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "f408d04a8eade097c4ae1905fac1277c4cdbe9d9fc63a72059e85c4ae4b0ac17"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v11.0.0+4/Clang_assert.v11.0.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[Clang_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "444a0a9f06d4a2b9044d95d664b44296d755edb1"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "bf2452b53f4505ad2ffb5f8c6857c3edf992097fa21aecb96cd849d4564ca09f"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v11.0.0+4/Clang_assert.v11.0.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[Clang_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "133aa665d70dc8337fcd156cdfa632279f43f7e8"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "8fd1fe790e99345aaf208e39ca7d95dbb14863faf758b7e977046258f056d2b3"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v11.0.0+4/Clang_assert.v11.0.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[Clang_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "fe8928e681e14a879ba248ab2937ea181574cf19"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "0ca235eb17dbb2c373a9f0f56d74dd45b8ff0c9d5b77260f629b511085cf22e8"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v11.0.0+4/Clang_assert.v11.0.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[Clang_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "42f3b3411ac2cf4dc632086d345a0641405baa5d"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "c8c316aa9a731ed9f03747a2a89c747c261d291209711360d6e7bf1e3328e85e"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v11.0.0+4/Clang_assert.v11.0.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Clang_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3cef9391745c9cac8d8e71edfd2d2ef98ef0c5f7"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "3ad2eedc52efef2cead188746f720deb1b83096e4423fabccd00b4b9ad470496"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v11.0.0+4/Clang_assert.v11.0.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Clang_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1580c3f19b863058bf6eb4af53e353fa5c9f016d"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "0ee372cb4bddadc97b3a18cdf15d6a771d0338f70e0d45fdfa6ecf3d20caf1e4"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v11.0.0+4/Clang_assert.v11.0.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Clang_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f41d308d0c767695bfaf1d6b73fd6836e741e6e0"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "22718406376a195ace17012b3b054877864be8a8e275366c4094ba7ba525ccb2"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v11.0.0+4/Clang_assert.v11.0.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Clang_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "da91c8db7a3ae1363c230c9cda929be05e0f92a3"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "d4b99296cc765966a51d2268e9219a3bf5be8f933e6b007af313d248e1fbfc26"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v11.0.0+4/Clang_assert.v11.0.0.i686-linux-gnu-cxx03.tar.gz"
[[Clang_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2664b87a4219a8ecaf7d9361f2b57b0a2ca3276a"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "d3f5a38ad49a9e6007607176707e4b9e25b6fa32e63559d8f15b08118db33dd0"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v11.0.0+4/Clang_assert.v11.0.0.i686-linux-gnu-cxx11.tar.gz"
[[Clang_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "091f69e66692ebb4bba2d009d5251316acb0c75c"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "5cabb33364ad5d241d981b04e7180cd90b1fe6fef2e2fecadcfbe2bbb1acf500"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v11.0.0+4/Clang_assert.v11.0.0.i686-linux-musl-cxx03.tar.gz"
[[Clang_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c2fd6a7507d582ded85bd69795804001a6e6c953"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "7c3f762a92c7bbc9d8029e009ce7a3a448c5efb93a9d7c4d08bcb61ca559167c"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v11.0.0+4/Clang_assert.v11.0.0.i686-linux-musl-cxx11.tar.gz"
[[Clang_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2b1615139cf52840171db2c0ba3958eef6c04231"
os = "windows"

    [[Clang_assert.download]]
    sha256 = "f538361fdf42d70f80b48f6ac08d7f0c06acafca32fb7fe261e9e322276515ab"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v11.0.0+4/Clang_assert.v11.0.0.i686-w64-mingw32-cxx03.tar.gz"
[[Clang_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5a7c5c14ece14506fb45bbf16744788f973d98bc"
os = "windows"

    [[Clang_assert.download]]
    sha256 = "6bf9cf034aca2b5c8f019084bf68f2d62ffc073d1db59a7b03631d480603f321"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v11.0.0+4/Clang_assert.v11.0.0.i686-w64-mingw32-cxx11.tar.gz"
[[Clang_assert]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4da00983935af95fa5ae1e5fa29da3753d81866c"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "594098620c2af85b5bb529caedcab7de5a8b5c4546c7d33ba5891957e772e7db"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v11.0.0+4/Clang_assert.v11.0.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Clang_assert]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "561713534761a3cecacf80d3e10f1e21ee4ec0e2"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "03ea37c0f3aa73d9a9113d084855148d3714379db0e768cab90c28375c488a44"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v11.0.0+4/Clang_assert.v11.0.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Clang_assert]]
arch = "x86_64"
git-tree-sha1 = "a4de5eb2b497a625db6c48b11a4e6fb4b49d5c3e"
os = "macos"

    [[Clang_assert.download]]
    sha256 = "71f5a619c5a7ae8141e8d3f90bb9751b2ccd54f83cb2d398fd65ddca5372ae3f"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v11.0.0+4/Clang_assert.v11.0.0.x86_64-apple-darwin.tar.gz"
[[Clang_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5f2ba9e70cf0390c865cfc1cc26b57a189d468d1"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "66a370a64b7ea2041cea1014634b1d8dd8098743594c85555362ac9111bc20f6"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v11.0.0+4/Clang_assert.v11.0.0.x86_64-linux-gnu-cxx03.tar.gz"
[[Clang_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b4abbd60e0e63903239ee0005bcd08af8f2d048d"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "e7a94b52fdd31440921ea8546431d9078ecba6899142a62a0305e4e53bea4b01"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v11.0.0+4/Clang_assert.v11.0.0.x86_64-linux-gnu-cxx11.tar.gz"
[[Clang_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f164bfc3c5d1341560b26e8e93c370ae1f4e3334"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "243435cb91020b8ff95208482847cd3b20e403ed52e4fccc860bbf8d7422c49b"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v11.0.0+4/Clang_assert.v11.0.0.x86_64-linux-musl-cxx03.tar.gz"
[[Clang_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f26ee1f2a2d59bc327d9c84d2fd2b048f26b6c35"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "edfd407212a891c83c25cd2ba1c3205b7c7e8748563fed656b3663d17a1f9fbb"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v11.0.0+4/Clang_assert.v11.0.0.x86_64-linux-musl-cxx11.tar.gz"
[[Clang_assert]]
arch = "x86_64"
git-tree-sha1 = "8e31a7104310f5f7e2a58c641c6bc21dba75279d"
os = "freebsd"

    [[Clang_assert.download]]
    sha256 = "9112b06994c842e002c3480b639f382f7cc0d87ef134f5716f44a7722be287d1"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v11.0.0+4/Clang_assert.v11.0.0.x86_64-unknown-freebsd.tar.gz"
[[Clang_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a12695c70fe7fcd2cfbc4659e90709c8c08f8a58"
os = "windows"

    [[Clang_assert.download]]
    sha256 = "3ade7d07417f1c428f0edd70a5d73e2ec0d1c23c2aecf22f58c4bfb0a2158849"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v11.0.0+4/Clang_assert.v11.0.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[Clang_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "809b73acc14a5f05b59180a9b31a2c5990802974"
os = "windows"

    [[Clang_assert.download]]
    sha256 = "7d9632222143abf665d8f402aa1972fbe8f8340969c66546cf0c39ea220c4ff6"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v11.0.0+4/Clang_assert.v11.0.0.x86_64-w64-mingw32-cxx11.tar.gz"
