[[Clang_assert]]
arch = "aarch64"
git-tree-sha1 = "d06b39456e8debbb61fad42c6fd2440a825b6d1c"
os = "macos"

    [[Clang_assert.download]]
    sha256 = "60fdf5e517a671f8136382a96c45ccbdd91e13389f41719de06ddcc33ebce068"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+3/Clang_assert.v12.0.1.aarch64-apple-darwin.tar.gz"
[[Clang_assert]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fc1b4bbb79b9270ba8bd8c1646a7dc8f386468b6"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "8ac8f18a044527c9529acd8ffbb8f08abdbf85702498d8f7da5c2291c09978ac"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+3/Clang_assert.v12.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[Clang_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9a6bef5616d19a80578c425294ead53251e01ccd"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "f330cd6c67e59d20fb3d19bb08b11e92a2107033faa023655e3f75711f2be4f1"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+3/Clang_assert.v12.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[Clang_assert]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b7ae4cd276858ebd632fed34585cd25c4b398a4c"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "6e3fcd4717345bb3db571b9d458dcd19b2496c93bd8806f78426d7c878d7a870"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+3/Clang_assert.v12.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[Clang_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "579ea421b92f421b5715d44c5f8b7a871e8a2d84"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "798610572c32c909da3b643d01a2dac449f4d163e127125cd14b368ef815d1c7"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+3/Clang_assert.v12.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[Clang_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "464182d47083e5139cda0399a9c9957f8934323a"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "d2f5ba85f056a1c14c63fad6e80ee63b031ff3e2dff3309af6da140b6868e002"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+3/Clang_assert.v12.0.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[Clang_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4a129c46a41613f29be42e093dd6cc7da75126fb"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "b85cb0959364926f3933c2fc6718b8ddd458133dbd018f8fbaefd75c55fb5cb5"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+3/Clang_assert.v12.0.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[Clang_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7b0e8eda96e84a64b6ff6df4e0432dcad05a3e38"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "2457800eb9bdec4f6ade6758f67c153324bbbe2c9529dc1b589e394453b50fa3"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+3/Clang_assert.v12.0.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[Clang_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "97d7b0c868fca432d7e206396328204ef16c92e9"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "ed30bd139d5f2bd89a31a15121503ff082ac82469977482ee032399efb1117fb"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+3/Clang_assert.v12.0.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[Clang_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "69d1f1335b4732bf54761416d0aab9bd4fa46ab5"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "2494c0447a940d639059906a3fe03f1619ea039c99115935a04d81741bcbdff3"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+3/Clang_assert.v12.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Clang_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c521471b54b6043af51f62216b143b42a7c2c5a2"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "9d615c2aee1ec523a8fd6ad03c44bfc61eea651bbf4dac93da9ed0e88fb8a8a3"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+3/Clang_assert.v12.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Clang_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "00b325e68c3d1bdb6dcc33e4bb96ff0206ba1d50"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "35a96910351d9331b291ec0e19d78cf1bf18dede8f181efb7e9541ad1a6226a4"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+3/Clang_assert.v12.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Clang_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c01feb5b595e2c6d981f9147a6c2f1542dd29017"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "b0066fc2ddbed2923b48aca9a933360918d0662c0cd8444b077231bfe06447ee"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+3/Clang_assert.v12.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Clang_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "58c35fab9fd3c64188d368438b008e0316794121"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "4fdf872d248179c019da11d29dec947380958623c7a948059a830692e366a9c5"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+3/Clang_assert.v12.0.1.i686-linux-gnu-cxx03.tar.gz"
[[Clang_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9acad8ccbda669ab7d096f718065a7d78f297ee4"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "5df059f111841558710b951d44bdb1e9cf3d210f41b0f494a35ee5e99df0bb0b"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+3/Clang_assert.v12.0.1.i686-linux-gnu-cxx11.tar.gz"
[[Clang_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "148b4547f3bf833c40cf90e8ef004ddf95268af1"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "8bd936679316701b3ff80a605e44c2d42317130002c542caf0fc2d60683593ab"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+3/Clang_assert.v12.0.1.i686-linux-musl-cxx03.tar.gz"
[[Clang_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "84d1711f1840a7764eb33df41aea1d6db93949d4"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "81cc7dfb8288be6a89647f00695d331cbbfe5a82dfc4a4018114291a4f1d29c4"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+3/Clang_assert.v12.0.1.i686-linux-musl-cxx11.tar.gz"
[[Clang_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6290b091abd9da1f37c61ebe5e8637dcd85d445b"
os = "windows"

    [[Clang_assert.download]]
    sha256 = "265c95554da93b6e4be4251dc48e23872f23994656f6f67796d99a59d95fee25"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+3/Clang_assert.v12.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[Clang_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f0acbc12a5b8db55a6e68b4b6710ad3853814f08"
os = "windows"

    [[Clang_assert.download]]
    sha256 = "c073ce470d9340fa5b8e5cc3358713804075c3071650306f5b62ebdf785cf5f6"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+3/Clang_assert.v12.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[Clang_assert]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8f60e8261be8390e5ccd9b005f39e48cf37982d0"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "b1c61a92438c0f5b91b5d143d884b762f6c77303244301a957ac42c23c092c66"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+3/Clang_assert.v12.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Clang_assert]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cd3e956b35ee2d3793aa18be12764dce69dcf92a"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "039552c673f0c6392b9b3ae313a6dc6a5e80e7d58c26827a1575c0b1880cfa5f"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+3/Clang_assert.v12.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Clang_assert]]
arch = "x86_64"
git-tree-sha1 = "166d7071e68615841f158c086eb98807582fbcb8"
os = "macos"

    [[Clang_assert.download]]
    sha256 = "6c3846f2fb6bc98660e677eb4e59c413e304240d81740f31a0d25b3822f8880a"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+3/Clang_assert.v12.0.1.x86_64-apple-darwin.tar.gz"
[[Clang_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8fd52eb524aa70f31fe88b0cafb906896f7eed85"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "50df85d4f3838c46cd45f3c21526081babcb1a7c32ab658e9ebc7eefbfc8e08e"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+3/Clang_assert.v12.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[Clang_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e97d194babc8d1228278f5a892deeb453ef2c3b3"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "f3e5ef41c5c2571dc3833fbcb596276e96940c578e960d3fc4e1b35e88e72508"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+3/Clang_assert.v12.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[Clang_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5e4a23a252658e7d1c3be3162fa95d389539f655"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "5b3855ce10b3420a3578b05e663e58c0afd0d666fc941a2d38d37fd94073b5b6"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+3/Clang_assert.v12.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[Clang_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7678c21f5000351c2502448090fcc033c1a60788"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "4d9318114941cc489f7e67a558637a8135117cce26788f6909c75313fedf9bc6"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+3/Clang_assert.v12.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[Clang_assert]]
arch = "x86_64"
git-tree-sha1 = "ff7866eb13152eaa2d27416876c048b0dba2585c"
os = "freebsd"

    [[Clang_assert.download]]
    sha256 = "eb7f023727f7495d60dac9e8d5f6d136e4e4c031c91d4f450932ae3d14f73923"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+3/Clang_assert.v12.0.1.x86_64-unknown-freebsd.tar.gz"
[[Clang_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a1b2d2fceeb1397612e5020305409e7cfa437b61"
os = "windows"

    [[Clang_assert.download]]
    sha256 = "c26ce26b43def1855814f87fe72cdc88c9ec9f03da82f2b9d53b290cd634cbe1"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+3/Clang_assert.v12.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[Clang_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c6b0ce71819c412533e4dd17df1922ed6b4c4c5b"
os = "windows"

    [[Clang_assert.download]]
    sha256 = "974899622afd3b646569de46a8456360979698997b64c641ac6ba323102da026"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+3/Clang_assert.v12.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
