[[Clang_assert]]
arch = "aarch64"
git-tree-sha1 = "5218e8884bf587ef4d1e4b35aede886e4e353fc3"
os = "macos"

    [[Clang_assert.download]]
    sha256 = "91b1897ed40e7c42e517d24779960c99e7f6ea64514e73c298cef471811344f6"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v11.0.1+2/Clang_assert.v11.0.1.aarch64-apple-darwin.tar.gz"
[[Clang_assert]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b02aab3b77f0580220efa782969b77f5af6e1638"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "73a4d60b1c3056fec1aef54bdf809327d7a37b79d5f3d4a2d30e03e5f55be0bb"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v11.0.1+2/Clang_assert.v11.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[Clang_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b01a422115b4d2e63cffcca09a9775c47aabede9"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "03e6115a2dfa05d63a8a14bc60e0764151217b7118fc844a6f81e787d4a97af2"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v11.0.1+2/Clang_assert.v11.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[Clang_assert]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bd01f2ab2cc883346f9f6b533cc3fa30e8b420e4"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "c1eb3401f9fa025859a498ea7a4a63e625c49027a016721f97ca564a63e0ca6e"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v11.0.1+2/Clang_assert.v11.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[Clang_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1a3cb05cb71d8d2890f99cac3b637c3d0ce63866"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "faef2f09bc9df05b24041b6a9bb35a77e32fbf12775dce8ff0f7c4d9035452db"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v11.0.1+2/Clang_assert.v11.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[Clang_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "91ec19d9e5424d3081add0deba26212a7454800b"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "0a8b91b2337df86622b581439f099708d8c3eb4b7500939c35298db17d32466a"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v11.0.1+2/Clang_assert.v11.0.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[Clang_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "db054ec5289398bb537dfd25482a3cb761dafbb9"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "6c753eda71f2a4bce8e95150d00306bcc810c58ec1ebbe3013740660e9c1c38b"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v11.0.1+2/Clang_assert.v11.0.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[Clang_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a7cae913eede17d4ab126319e460d65482493114"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "1a17410d28ad6edef978969dbb1bf47565a7f5bc7b86613c928afee7a286b964"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v11.0.1+2/Clang_assert.v11.0.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[Clang_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5c556dd047e05641e55f33792afbeaa827f844fa"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "aa5da34f45cf3b800c7eb2cfdc37b8381f2e201310f413be8292c498ea981c4b"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v11.0.1+2/Clang_assert.v11.0.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[Clang_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1efbbf2bcddd30c625bc08f2e4e6547329125e5e"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "b5d51b5e27028e97287d684b55d38ac0cf91d1c28dfeb7de9644e66b081cbe74"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v11.0.1+2/Clang_assert.v11.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Clang_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d650303462ecc5a4d003a970d6bb0a6d9eda39a1"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "276be85ce4b3f8d09badeee93f890bc5db54bb7a7d0ac399525202ba951d4cab"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v11.0.1+2/Clang_assert.v11.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Clang_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "670ce9e3868b1f770c96aec1c429bee254020512"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "e97c0e2f82b0b60fcae5d13307735924f42e1fbafe78deb4145b2a28244fe50f"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v11.0.1+2/Clang_assert.v11.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Clang_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "38fc535681991fa31833012735702c4047393f34"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "2d6dd358071a91f40a6f6bfbc86ee4eb615e79aa923bd60d3a73275bb3047ec3"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v11.0.1+2/Clang_assert.v11.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Clang_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d5d7ddc79e79c0e18a2fc8ba3e84eacf653b3a2c"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "09fef3f3dedd1c23ed446407d595e1327984956bfff852a726e876c8ba5311b5"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v11.0.1+2/Clang_assert.v11.0.1.i686-linux-gnu-cxx03.tar.gz"
[[Clang_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4fae9e78e76c92a716d1b25c362f3f6e177993fb"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "4f6af2084dd58d4a7e1db167cc2203e112308e8bbac70daa6bb886161349615a"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v11.0.1+2/Clang_assert.v11.0.1.i686-linux-gnu-cxx11.tar.gz"
[[Clang_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bde1859f2ce49f4956e828e9b815cea8bc8fd247"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "6f3e2c86f49de044185159481270646a59ce9e0b8a09539fab22fcb9eab74a09"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v11.0.1+2/Clang_assert.v11.0.1.i686-linux-musl-cxx03.tar.gz"
[[Clang_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "29c2326735c9bc019fb8f890ffc025f873db4c72"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "9b5bec20521651bd8b9be2f6d1551cb901df690a70e0af99eb9e2dcfc3d4a915"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v11.0.1+2/Clang_assert.v11.0.1.i686-linux-musl-cxx11.tar.gz"
[[Clang_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2caff6f1009e247cdc0a0cfe423d72b744a7d12c"
os = "windows"

    [[Clang_assert.download]]
    sha256 = "0cb4a4ad3884400e0928d2553e2abfa86f3fe90b1da52adeed21fb916b91d079"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v11.0.1+2/Clang_assert.v11.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[Clang_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f380994d2d12ac6b3e38d1d1efbf77df71760125"
os = "windows"

    [[Clang_assert.download]]
    sha256 = "d8d52bbdf8aba61ba79bcbaaa307d3c3320e679c3f4891182ce55b6a8b76f642"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v11.0.1+2/Clang_assert.v11.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[Clang_assert]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b56f2cd89088625868c9ff750d0cc26a7ba668f7"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "c665e894527cf1c1be05b8bd32fcf8c3c0e9aef07d67e5226aeec33f6526b7b7"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v11.0.1+2/Clang_assert.v11.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Clang_assert]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2e98ba14bd5647ff60fd6554d4116d6085a60d1a"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "f1e6ca9f3927ab1ddb8a492c5727d670f4481d6960b769002aecfb49a537b401"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v11.0.1+2/Clang_assert.v11.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Clang_assert]]
arch = "x86_64"
git-tree-sha1 = "0fc2c99c203b2105b886e7f33978ab49341b8bef"
os = "macos"

    [[Clang_assert.download]]
    sha256 = "8cf268d8b8e38a421e67cff6e9722f6b3e6111a1e25eeea248cec0b7a1fdbc19"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v11.0.1+2/Clang_assert.v11.0.1.x86_64-apple-darwin.tar.gz"
[[Clang_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5c7f36352fc634abb6393ff20368cf80d08668b1"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "86850085f10daee7c1087715a72b34285f481e6e5713e81402557c2e9b3d762d"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v11.0.1+2/Clang_assert.v11.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[Clang_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "12e39d2115e08928ed32e1aece6b8f0a9834c328"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "a525e085200ee16e72e4ce536be1679ec519c8b3fc37b418a1a3f2f0a3a2afd6"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v11.0.1+2/Clang_assert.v11.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[Clang_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "889e26e0e6a47eb7a3fc1b4403b9774a65f56fce"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "2853c0a020a201c4eba71db0315c080e65f493a207e617f740a594c30a9ea3b7"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v11.0.1+2/Clang_assert.v11.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[Clang_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ce63ffa3d153eb0e9c6e1fe9c9e8786ebba52205"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "a7a6a4899389085bff7804596204eddc8ba102aa9e04d0a63222ad168b528852"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v11.0.1+2/Clang_assert.v11.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[Clang_assert]]
arch = "x86_64"
git-tree-sha1 = "0afb78a7bb56f5bfdbd63c065ea743046b550c31"
os = "freebsd"

    [[Clang_assert.download]]
    sha256 = "1463a00c6f6f9358b90a50eb7feda8b65a731d9b40355be9ba34d5839f156888"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v11.0.1+2/Clang_assert.v11.0.1.x86_64-unknown-freebsd.tar.gz"
[[Clang_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8587b317c42b04fb84aa72e2a1ec71abe2ee72c8"
os = "windows"

    [[Clang_assert.download]]
    sha256 = "21e2cbe978ac06f9d7b4ff6d3b9214273d1b36630ab6bfc7e3d693d917b45aec"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v11.0.1+2/Clang_assert.v11.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[Clang_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3d5ccda0fba5e9fa3fddd10df1a560aba3668061"
os = "windows"

    [[Clang_assert.download]]
    sha256 = "57b59e7840a8b7f1323a9437489c188a32d17f7ae5564b90f78b9803f1c3f329"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v11.0.1+2/Clang_assert.v11.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
