[[Clang_assert]]
arch = "aarch64"
git-tree-sha1 = "8f1d5275af6268cc3b43619664980ae24e07f838"
os = "macos"

    [[Clang_assert.download]]
    sha256 = "1efcb0d7f2a80329efd08c2e921ca6b06bc13b06f0932c32fc27477c578912e1"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+2/Clang_assert.v12.0.1.aarch64-apple-darwin.tar.gz"
[[Clang_assert]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cc2b5fc438b3af4c86bcda5207b34b9e3f435a09"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "827a954f25949cc34f5959f8d0e3900d3e1e584864d93b450fe5c61126399814"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+2/Clang_assert.v12.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[Clang_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "11862a8b50b69f4e94fed4faaffec944dd99b851"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "d8a08b524c7bcfd02f9b2e1b1b95b26b21e1edfba822574031f7c948acac7015"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+2/Clang_assert.v12.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[Clang_assert]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2b2c28739262e888f60248090a4ffff10381c650"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "3b0145d7b9f589939e97a089e306eb217bc4f84f0abaad297fe6f2324e9b8273"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+2/Clang_assert.v12.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[Clang_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "045786b41d2a16e2a8b0e2cce5f82e1e94d60bfe"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "0f7ddb660c6d9ccd73b970733bbb47147441698636e0bdca26eba29e83cda625"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+2/Clang_assert.v12.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[Clang_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d279186df5389ce6223fd154d240b4fb55384247"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "f2272735548f8fb7133fa4f4153538247ef48bc63130ecfb05f8b04cdc436370"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+2/Clang_assert.v12.0.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[Clang_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "572b30f556917c9cc88bf3473fc2ffa7698f84f0"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "13eb1a06bf60129a8d6af30ce5bbc8c659a0605af3d4654e33bd662cea2d7f95"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+2/Clang_assert.v12.0.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[Clang_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bf976598cbf90171c738ed8e93778fd4ae4c6ba9"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "3d6c90ec7214e85a4bc878d60f4059bd52bd617d774c822b13861214509265ce"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+2/Clang_assert.v12.0.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[Clang_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7929d5435cbffb595951b7c2000b652134819bc4"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "9bf809fc449f456d857db11082fc386ebcb5c9e35248f0638c9e0ec31f4d9027"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+2/Clang_assert.v12.0.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[Clang_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "846eb1ad9495c6833db7a864c48f225387ac7d55"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "48186774a32400ec540b17f6540d65f058e39364ebfa68334477f392dff730ff"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+2/Clang_assert.v12.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Clang_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "44b68b1fb59591e87fc48f07696991518bdb6d31"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "98786cba20ac40ecf9ecaa1dee1b5b4bc4b9051af98255e3eafd389ac18da18d"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+2/Clang_assert.v12.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Clang_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6b49da6de2481d08a6e91535603c1a182a5014e6"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "d0e08622a055cdc830587b5bca3c4bf7d7b74f0b3e309b27f14758d35464fbd0"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+2/Clang_assert.v12.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Clang_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "683e3d1866c32bf95d9822f4eadffe18a57eeca0"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "c3e04b8a4810c26ba38b0a2b1a01b6c78ed1cbd2e4c36c174723438b93d9756b"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+2/Clang_assert.v12.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Clang_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1e929e06606d478fbab4d17f669bd0023bcf7a04"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "771eac18b5a2c486c0255abecde565d489edb51e17d0b542d109cecbb41d5753"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+2/Clang_assert.v12.0.1.i686-linux-gnu-cxx03.tar.gz"
[[Clang_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "824aad4d323ca95205b8733d99bc683316e7c8c3"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "02cd24965c4e92b21627784b6a3f0bdb9063e59a6a138c196d905c5a42315a69"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+2/Clang_assert.v12.0.1.i686-linux-gnu-cxx11.tar.gz"
[[Clang_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6d01324f6f5081b8fc459680e3c0aff6c17979b1"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "f54ba75afd18d3fff3b0146ebae0c1e3f9126d21161166b909cde65f7542a384"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+2/Clang_assert.v12.0.1.i686-linux-musl-cxx03.tar.gz"
[[Clang_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f2221538d56e033e135249ae86c28a22463fdaa3"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "562ebec7b7e869174fa1ad43a610bd6e6e711aec0cd47a070ad203913cd575c8"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+2/Clang_assert.v12.0.1.i686-linux-musl-cxx11.tar.gz"
[[Clang_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bb3a81fc0e0b76fdf426ccd8b417b8e533dbdb95"
os = "windows"

    [[Clang_assert.download]]
    sha256 = "2a8dbf3ab752f7e73d9e6bb2e30cc7174c435990a09e69849fcc7dd5be3f6b38"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+2/Clang_assert.v12.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[Clang_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0208f74dd6f6a1d56fc16a8a660eff25f10460ca"
os = "windows"

    [[Clang_assert.download]]
    sha256 = "7033c11211bef51c1c56025776805dff30e79abd7184d1b00519355a38121b02"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+2/Clang_assert.v12.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[Clang_assert]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a8c5bda1b7006a4bbc871f2778fc56674f5cc11b"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "4ecfd6592a929ee8cb18f28923ef052e63604d883a4d0c708b5641f23a58c860"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+2/Clang_assert.v12.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Clang_assert]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "04efd1940a20ad53c886e7519c8e8b5ec7e01272"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "e03bc82a2f8dfa67fcd24da15abe79cd571fbf9c6136bd995120368a18641563"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+2/Clang_assert.v12.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Clang_assert]]
arch = "x86_64"
git-tree-sha1 = "381c153b23487f280a2261591e477841fe26580c"
os = "macos"

    [[Clang_assert.download]]
    sha256 = "bf5e4d213d03de24d9c7923b23ac80b5ccdf837dbcf022c6f0ca54a9c59aadc1"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+2/Clang_assert.v12.0.1.x86_64-apple-darwin.tar.gz"
[[Clang_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e37879a6547b7ccb48670fcbfb95bf0a3e61f88f"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "b7d649bad911bc51af8ee3309f42bd933af4e6581e6e4759cb77300289f481a9"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+2/Clang_assert.v12.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[Clang_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6dedee8b157c9a575d4389f26128c5d882f74a23"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "893d176658826baf1ea502d3a5fb7814d1181790fcc2d1448ee9b14fa452a8ef"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+2/Clang_assert.v12.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[Clang_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "37eae86833676684de1c8dde3f6f4fe043d3e87b"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "5420249af75d42354f5c30c5a7a75977ef51138b7b927b6d08d974887ccc3100"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+2/Clang_assert.v12.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[Clang_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4ef1a235a97c337d87bfae880e36d5d813a45fcd"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "abbeff7a611f068236cc0ca358fb68885d92a3196509a993c19d90c5e4acf3a1"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+2/Clang_assert.v12.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[Clang_assert]]
arch = "x86_64"
git-tree-sha1 = "198eb2f8d37568ef518f6130b5e5b33ef76b0761"
os = "freebsd"

    [[Clang_assert.download]]
    sha256 = "1cdd0c6fb9636042c24f348cd31a5fca3a8cc285b0b5165018a235aa1c3c9dd7"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+2/Clang_assert.v12.0.1.x86_64-unknown-freebsd.tar.gz"
[[Clang_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9597f721b2072cb8b95d39158a2522602d664d94"
os = "windows"

    [[Clang_assert.download]]
    sha256 = "d15f7397c125a1965f4452c1691843bc7c83d41663bc74fbe60d84650f745659"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+2/Clang_assert.v12.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[Clang_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2815b256e495643874d54c318d9b3cbe1e761047"
os = "windows"

    [[Clang_assert.download]]
    sha256 = "3bacc43415bf0d071bc04181b4d23a92ba14bebd7498363f51b4a89e55214db3"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+2/Clang_assert.v12.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
