[[Clang_assert]]
arch = "aarch64"
git-tree-sha1 = "09d226424cbd861633ddae8e13c50f45bde97c8e"
os = "macos"

    [[Clang_assert.download]]
    sha256 = "acf6279c1f164ad19d45f1676455fbf7d81ee308a427e00a98e857f2d4e301b9"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.0+1/Clang_assert.v13.0.0.aarch64-apple-darwin.tar.gz"
[[Clang_assert]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c6e6062aec894eefe3ba9e662f25485b7e37e9e8"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "6c6cc5963aead06a02d2c83139e406eb514dd22c9f19cc0ee8a41e0b4050f194"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.0+1/Clang_assert.v13.0.0.aarch64-linux-gnu-cxx03.tar.gz"
[[Clang_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "64b7b0fe96e993a4fbf1e2ae3c9a2d12507d9a39"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "3121b41a1c5e179ceaae4a4af147e0fbeda1ff1dad9c84723c588bbad5932005"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.0+1/Clang_assert.v13.0.0.aarch64-linux-gnu-cxx11.tar.gz"
[[Clang_assert]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a9d0e8b978c8cbc48434aee897e2aeae1de86282"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "f5a24a36dc713101ec417cca336c02c8a4ac2e73fd897a40394205b81c9ba58d"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.0+1/Clang_assert.v13.0.0.aarch64-linux-musl-cxx03.tar.gz"
[[Clang_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9ea57894ef3a3ef61a8b850eb3b27d9ef31c418f"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "d077a65253a8c1a41cc9660237571db7228e57343ecd44e731e69307863eacc0"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.0+1/Clang_assert.v13.0.0.aarch64-linux-musl-cxx11.tar.gz"
[[Clang_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0e55a49e3e3c838fbebc3e5ae212a965e9eea239"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "f0168b99eba5f77e7ba13ee95921add30d92ef5abae3187f9a22719cb030ce51"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.0+1/Clang_assert.v13.0.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[Clang_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f6f7f2b0a1df7c74d06401b591dd13b16490b2fc"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "4d2766ffb6ebdb7f943292f14e4214d279cf64caab676b802b43c785905c6563"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.0+1/Clang_assert.v13.0.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[Clang_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "97090595bff266ab36b894b9aa3f064b9b178449"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "e2853b8035cd9e2b30be6ed3f6ae3ec566570acb979ad5d58c4e1620370b2926"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.0+1/Clang_assert.v13.0.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[Clang_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a821ae8510585106d6d0801a4804d9cf41ab432d"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "8b8350b136df4ed46370f841f34c2424e5db66a4b190c531d20d6d114593eabc"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.0+1/Clang_assert.v13.0.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[Clang_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "67f43926e2c22398659dab47edb9d277b8ca169a"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "76aa46d2170bd032a711bf868382a0e8340c8d8b63c17556d4cd7549fe5c022d"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.0+1/Clang_assert.v13.0.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Clang_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a080ea406ed04c1a42bd224122ed6d61d43b47b4"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "8abc6b4d8d5f352bbbd3b7dbfd35eb3a92d52f761eaa3b9e0b51c349e3b75401"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.0+1/Clang_assert.v13.0.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Clang_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f94d1d7412a4c35c1edaff8f59ff4bf680057ba0"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "5e320d1bafd1ef4b811a6cb097c96cab55a2050916e8f7297eafccf720422439"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.0+1/Clang_assert.v13.0.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Clang_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5d4175c916fab8ad480a46d6fe61dcdd99ab0820"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "d786e7d3d6ae74a29496efcca53bded7408bc87c0fea673d10153c29f3f31013"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.0+1/Clang_assert.v13.0.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Clang_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "488ca02912e2f6011681d84b9783b9547e393cad"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "2c969781365fdbfe887da675b33669f99d82d6b94b16cabd56e2916337cc9d72"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.0+1/Clang_assert.v13.0.0.i686-linux-gnu-cxx03.tar.gz"
[[Clang_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8d09278c613031262390b15d4fbea3b8b434a868"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "e9508f67c5a555dc4d5d50b8043cf14e6ae0a48cf93a67efd680681428db00a0"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.0+1/Clang_assert.v13.0.0.i686-linux-gnu-cxx11.tar.gz"
[[Clang_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "747f4162866798573c2544a3fab7150b8d259e43"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "5a03a9a11dfcea05de4d1c39060863d0a54f4cb716fefebf175357670576efee"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.0+1/Clang_assert.v13.0.0.i686-linux-musl-cxx03.tar.gz"
[[Clang_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2eec37dc1d32912ed632e67a3dbcef72ab6c6385"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "01986b5cae1c98eb332f0d19036e95648ce0985b2629964c9616d5505a57bf69"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.0+1/Clang_assert.v13.0.0.i686-linux-musl-cxx11.tar.gz"
[[Clang_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "607cccb2a6413b6195c11a7f41a88ab99d0cb44f"
os = "windows"

    [[Clang_assert.download]]
    sha256 = "56adc9a1da4512d49396365c2d5cb67104d8f5f570a62f086232ba7a1d85872b"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.0+1/Clang_assert.v13.0.0.i686-w64-mingw32-cxx03.tar.gz"
[[Clang_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f551a19d41707d83b5ed5737dfd75a80e659e6e1"
os = "windows"

    [[Clang_assert.download]]
    sha256 = "c87d4c0e483e759495eff703b3c3dec0ba3bf28113d3322d7958acf088c9dc83"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.0+1/Clang_assert.v13.0.0.i686-w64-mingw32-cxx11.tar.gz"
[[Clang_assert]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "191179cea90c4fc7eb137a5aa324e91a9e364ff4"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "3fca3ba41ab42f31503c161b0e33ee176c3f275657bf3ec20dc7587d3056d9c0"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.0+1/Clang_assert.v13.0.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Clang_assert]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "623936e91ccbe5678702e94fbb0027dd79a4bb04"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "d9507c3d32cd83ad9da368be49f4870124598c4bbd34902abb774177bbc00b7e"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.0+1/Clang_assert.v13.0.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Clang_assert]]
arch = "x86_64"
git-tree-sha1 = "5550de9ae4bfbcfe5bd22d3f57b370f40a134ade"
os = "macos"

    [[Clang_assert.download]]
    sha256 = "2727960fc1afc420721ebda2d8a2e0b4f13330dd270bb80299d1a615e2f34ec0"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.0+1/Clang_assert.v13.0.0.x86_64-apple-darwin.tar.gz"
[[Clang_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7ea41b0e16665dbb9c3ae9a462857705e6e3f0cd"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "65fbff663c37ca852e3cd14e9407ad5b3d93beca904810746fda6f6d0543fbb3"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.0+1/Clang_assert.v13.0.0.x86_64-linux-gnu-cxx03.tar.gz"
[[Clang_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ade0d044ea660b763d0ed53444de31f3c43fcccc"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "d72c72ccb753c37c261c448095df50fed63ea12091aa5e649e57e3cf20d17663"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.0+1/Clang_assert.v13.0.0.x86_64-linux-gnu-cxx11.tar.gz"
[[Clang_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f33f07e5c8e0d31642332ad91647af7cf901e5b5"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "2e89de10a20450ec2a9c025af4583eb5a56c5aac84f6da8240b37b8c17c76750"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.0+1/Clang_assert.v13.0.0.x86_64-linux-musl-cxx03.tar.gz"
[[Clang_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "801854f8335abc143c4b1a5b3b2b0be96600432b"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "681ba6ae9a17ca1895ecccaea373b7d5844f402d8a23c2afce49faa95b2bb041"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.0+1/Clang_assert.v13.0.0.x86_64-linux-musl-cxx11.tar.gz"
[[Clang_assert]]
arch = "x86_64"
git-tree-sha1 = "7917d5cfa7fcb05c03bb523eeb74dbbe954728de"
os = "freebsd"

    [[Clang_assert.download]]
    sha256 = "6d1fd4f1c61a72e195130782276cf8272f75f82d1661e1a265580ea939e13e53"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.0+1/Clang_assert.v13.0.0.x86_64-unknown-freebsd.tar.gz"
[[Clang_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9598243ea6e6e81ddb545b33f161c9e8c110be5a"
os = "windows"

    [[Clang_assert.download]]
    sha256 = "0857bc419f9c32577ed4efa5471866da3788a60bf0ca8c3c80b4f7b13d8678ac"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.0+1/Clang_assert.v13.0.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[Clang_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d33ab854b9155e29381afd2d32bdd5ffec75926b"
os = "windows"

    [[Clang_assert.download]]
    sha256 = "38f1e89ec97da321b63dd90ab7bda1efaabc08ee8a69866e92acfcb80aeb4d33"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.0+1/Clang_assert.v13.0.0.x86_64-w64-mingw32-cxx11.tar.gz"
