[[Clang_assert]]
arch = "aarch64"
git-tree-sha1 = "6e4dbc2b3f688607e7a90a850fdf6d9071b1b887"
os = "macos"

    [[Clang_assert.download]]
    sha256 = "d378dc9ee87a0990ff44b026a9ab5d81832275f1b4843e9400756e088d710b0c"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+3/Clang_assert.v13.0.1.aarch64-apple-darwin.tar.gz"
[[Clang_assert]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b5f0a0ba3ff239d1420193f7c2e2aab683427c05"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "b5fa67671c2667972aadce976b89f635648490b781801e6ec4a97dce2045e0b5"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+3/Clang_assert.v13.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[Clang_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a9ad7d86e288fb12ad10333dc753b796e040b332"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "76fce66ed53de846e3fd73e4a8b8198af01c42efb362451dd968f7250ec23158"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+3/Clang_assert.v13.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[Clang_assert]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "473eb67e0429d7e0ec5a0ed302a9ece1504c38a6"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "48678bac6f50aaba21d021af180ca7add734e5f6ce958e4a87306e66b0244404"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+3/Clang_assert.v13.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[Clang_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "70934f99a163af1a183029775c8e14807a0961ba"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "5fe8c97ec98886a4ec018a3fb59e6b19a4e85b246b32a08a3bdecf0420946b95"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+3/Clang_assert.v13.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[Clang_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "931b75dbb69a64f2c88519b8b6cbb8ef91a3fd36"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "2894b1efe385e13914c5714071cb4a4853b56dc8cdd9256dc675591d5593bf14"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+3/Clang_assert.v13.0.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[Clang_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ff2ef7a9a0173df7b8727023b1a02937731c87aa"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "b40fac8eca69fde6bc996b54015be32c6307a757ac68cc49331064057bea75e2"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+3/Clang_assert.v13.0.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[Clang_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ce1ee77564ab19cdf318c0f07d8261e24ac91ebb"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "3f9eb6819b2c632e21b66d2bcc9b96c49be746bd27c4aa969faebaaf3e949655"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+3/Clang_assert.v13.0.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[Clang_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "645d939eaf6a1af63f0b76861975fa6489d06e05"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "31439ed3ea3036a1b403d528990f09e934c87dc18e05862714b750a5e9ff6a8f"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+3/Clang_assert.v13.0.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[Clang_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "0b78072ad668f0cc7f06e10732ffa69c5b15820e"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "9087973a93f5a73079aa28802f2a4937ed0015b9fd2b108e604d3bfac89fc9da"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+3/Clang_assert.v13.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Clang_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "89aad93d0096bdf5e3e8c297d9692b38d5f04a52"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "dc342c1f137a784cb264fc6a89e7087417cebc7f5a797493d6b15dc1024bd591"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+3/Clang_assert.v13.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Clang_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1edc23f219fd5ff76778289d59bd6079a59aa25c"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "38629a4461c1eda24ec91dbd4217679ed3656c2fe4933d39a9f7ea639e44dd88"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+3/Clang_assert.v13.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Clang_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ebf3fb45b4779f71909991bb9b1d16cd179823cc"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "82d22d0adecc68eb04e56864f4b3983ec5ea9a28c73b3655b6db4e2bb98671c6"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+3/Clang_assert.v13.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Clang_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "28d1fe800474c34c5cda15a29696d117e589afd3"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "ad842e020b66e983376bbc2ecdeff43054a31cf21228241a21ed8e9c1daba8fa"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+3/Clang_assert.v13.0.1.i686-linux-gnu-cxx03.tar.gz"
[[Clang_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1eb04dd76fee290273dff2aed7fbbbba081a2425"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "57d3a4f5bb950adba1316b65de142e3726ac56bdf180af0a12e38ee8e50f5544"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+3/Clang_assert.v13.0.1.i686-linux-gnu-cxx11.tar.gz"
[[Clang_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b62a1cfb394bd2dcd924b73da43a79a4a6bfd5c8"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "b6f38e85718a2ffcb75bd225249fa723f9f82e8e67f80c103d6ef761b612af27"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+3/Clang_assert.v13.0.1.i686-linux-musl-cxx03.tar.gz"
[[Clang_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6a31fe6a999f418d7d7f09902d47e8e2a43fa28d"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "4c88c5e166021962bb4ff02628002992aa3c5533b3408e77a0cb6c865b7b9466"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+3/Clang_assert.v13.0.1.i686-linux-musl-cxx11.tar.gz"
[[Clang_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f710f3f02c044d80dc969930e032308f5a23a49f"
os = "windows"

    [[Clang_assert.download]]
    sha256 = "a23cdfaf06319ce2630b8b545c9eca50dc8347db162b3d6960ce2efef0ae2f8c"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+3/Clang_assert.v13.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[Clang_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8af49d549e3c0efa51ffc2971d69ec03be256d5b"
os = "windows"

    [[Clang_assert.download]]
    sha256 = "06a21486f1d111e29a599533bbfe81df695de166e2b4e04dad036be8b289a03f"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+3/Clang_assert.v13.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[Clang_assert]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "72b6f3699f617f6ba374044880ba9132657580c8"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "1e38af5f0570a62907ab07ab5879bd1a52a360af4d33d79473a28cc959288402"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+3/Clang_assert.v13.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Clang_assert]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e057704eb2639e60e9ad79cc78fd012d6feb1f51"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "4a0979edcf135a1b75ae1be8e08aa63ac3d42ca29c8fccf4fdcd1ada6a7de44e"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+3/Clang_assert.v13.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Clang_assert]]
arch = "x86_64"
git-tree-sha1 = "05b43628538fc9d2496b4f5c5d3f954f42dda2d7"
os = "macos"

    [[Clang_assert.download]]
    sha256 = "0d05981d4a7e981979030c2c825370ffa52115f0ea2fe8b203c8f9caf0343ba5"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+3/Clang_assert.v13.0.1.x86_64-apple-darwin.tar.gz"
[[Clang_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5a134ffaaab14ced00877880ad3eaf8dbc1e30b0"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "cc971f7efa0ac4f9f33e121163348406147898b439a100f5a3e22021b692f63c"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+3/Clang_assert.v13.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[Clang_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "66997c470c334ad3ee1f1a6e990b5b3afe379691"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "5b3ea506ec60824b737cb4881c75fb4707e94ee02e15fff2b0d39adfe6e2fe8d"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+3/Clang_assert.v13.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[Clang_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "97771eb8c94cbe4d2457c0011440d83fc7c5d005"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "b60a53cb733dfcb5d87a9f9cd189b0c53cd7d7dee669a5aca51d437262785a04"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+3/Clang_assert.v13.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[Clang_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a9dd3231f034031b4ba2b4fc8d05d40282d84713"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "8fa14bbacaf9f6122a37dd7f18f7f75fcbbd03cf5c73e7d1daa2866c2f5944f9"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+3/Clang_assert.v13.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[Clang_assert]]
arch = "x86_64"
git-tree-sha1 = "67b808cf3c1ac8272ab679f755fa81f8fb9f6000"
os = "freebsd"

    [[Clang_assert.download]]
    sha256 = "8f5009fe81fe4c8443d0f6c2dcd0f223e56bfdfceb78bf09baec6829ede7b8d1"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+3/Clang_assert.v13.0.1.x86_64-unknown-freebsd.tar.gz"
[[Clang_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d5da553daa95e95815080bd6a80c2af112899dfb"
os = "windows"

    [[Clang_assert.download]]
    sha256 = "e746b7807bd9a1ea1a31e8601ff4d66e0620111dc55b1e3ebab69e5cc772a807"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+3/Clang_assert.v13.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[Clang_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "e42fcd0ebaf1cad3d05636868f38ac18a688d1b4"
os = "windows"

    [[Clang_assert.download]]
    sha256 = "5ed1e48d3d7021c28cd45b74cdfb80a6fc2d5bf9f78db3549aefcad3d326d53a"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+3/Clang_assert.v13.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
