[[Clang_assert]]
arch = "aarch64"
git-tree-sha1 = "245478b8680194e770f846e0e595a9a706955e4e"
os = "macos"

    [[Clang_assert.download]]
    sha256 = "df45c7e8adb4e3d2ca3e89c45fda79c573ffcfcd7f8d59ddd9ec20c59dbad48d"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+1/Clang_assert.v13.0.1.aarch64-apple-darwin.tar.gz"
[[Clang_assert]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ddfce28d5e846add17ce0d048a3fb01753b67572"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "a77b9267bd4ac531418c7a74ff7b31e30079273da727b921d9dcd568e73fe09f"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+1/Clang_assert.v13.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[Clang_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "682be247cec41d2c94a38a81b44952b2d457906e"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "0e51aac179ccc8eabe79dbfae8b3c44988cf19ca3c8d0907f1af278e235d9b09"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+1/Clang_assert.v13.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[Clang_assert]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "068931efa957959ad01acf014200d783d7ca7d14"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "5c84626fc057b1af5169138c8b9b6d00adbad1d7e4736538eec093848f7730ae"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+1/Clang_assert.v13.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[Clang_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3c849655fa5326cdb35c4aa98e0ac5f8d3aa0607"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "b992111c46ca931996cb3db6bc65391d9908e87edc68d038b3018cfe66ecd543"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+1/Clang_assert.v13.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[Clang_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4603c007a1dbd0f7966d4da9ac622c06215db74d"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "c957a0bfd8c4db2d09f840712f6b684f897850e47bb58dcbb0acc9ded6eba1c7"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+1/Clang_assert.v13.0.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[Clang_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "798473654002740b54449db2cbe7efa7d05a9cec"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "62e1e2a2af70b51a71da66a410e4393ce0f1404adcdc089c3226990e84d21d59"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+1/Clang_assert.v13.0.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[Clang_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e5e4918d88d161e58cd5f7a3147025323a4f6e7b"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "bac6ea866bd79b372fa1d666e31a0b298fbde314e97aab1428935a7ee392476e"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+1/Clang_assert.v13.0.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[Clang_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f1d01da58d37956ae43806c056dbe1aa5a2fa36b"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "19d80571c77508b7f23ece101ab40f7b8ae254035ec9f622444e159cac850adc"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+1/Clang_assert.v13.0.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[Clang_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2e5e312b58a7f54b222adda05d2f4241a04bd05a"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "a3149b9af2045ac659f2df3d6ebd37184c2f2a7a59779bcdd425ae3b3aaf0c7a"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+1/Clang_assert.v13.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Clang_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f288c88c6f522f3e411dcb53545e9eb88ebf4ca6"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "37dd6a7b968c2065967f55bb294e1a6468976dfda3bf2e368a932c9d5379856c"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+1/Clang_assert.v13.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Clang_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b884384f646318998e65d05fb791c18a3c621f90"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "2c930d35ffd0120645576697b4f65c9d6961f45cdb11a1c703c35a988455ad0b"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+1/Clang_assert.v13.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Clang_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0f7c44beac064fc83e22281cb3ff5d1c96169806"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "3158b70f7e7eb88df8689382e6e253813d47f9379d3235130ef723ea093880f3"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+1/Clang_assert.v13.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Clang_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "dc1ee3b407c02a3716e079ffcf327c51900eecbc"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "da95f0c869e5493bafbc20474cf5eec7f6eecc3ffa4766a1d8303a13d403508d"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+1/Clang_assert.v13.0.1.i686-linux-gnu-cxx03.tar.gz"
[[Clang_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "06ba851d8f8e08685cdd9dfd3dc47dfa7a83b93d"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "f3d276431df3b8ab773bda92c29fd47c609e33e46fc80d88f065310851ef0ac3"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+1/Clang_assert.v13.0.1.i686-linux-gnu-cxx11.tar.gz"
[[Clang_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b273a8322dd8f396bf237999f06b111366d37535"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "85f812d8952150d703162f5082d016f5eb93add693374a40fcba8ca7bd92e5bc"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+1/Clang_assert.v13.0.1.i686-linux-musl-cxx03.tar.gz"
[[Clang_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "eaed0f1b298526f4cfd73bac8b54b72b8e2fd672"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "dc1d99fc3a25864be71c928dda006a4a039e3844005f927e8d162c55eca87a35"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+1/Clang_assert.v13.0.1.i686-linux-musl-cxx11.tar.gz"
[[Clang_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "db7dd8785c32b0864664d02b3823c5725e4443b3"
os = "windows"

    [[Clang_assert.download]]
    sha256 = "336ab097cb9e7e840d0283588ba7c606ec6f2cac54d67149cc6069ebab76d680"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+1/Clang_assert.v13.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[Clang_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "63030bea63f83fbf721603fda47e0d1c174a875f"
os = "windows"

    [[Clang_assert.download]]
    sha256 = "18b4af45fe891917d80bf0ffa29b5a562919259c29e427a2035ee441c9582275"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+1/Clang_assert.v13.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[Clang_assert]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9216c0d2aaf43ee13ccb28b226ea31b68ee5307f"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "23d7893dda5f05b422690c9a8d119ca2287cf4baf9f245dfc176d66bc98ef8ff"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+1/Clang_assert.v13.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Clang_assert]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "039599d95c8d44945c0a2c4704804da3a344a6c0"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "9287749d919129ae0da415574ce4e442ac35ffdb3782aeda0c7466124270cb95"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+1/Clang_assert.v13.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Clang_assert]]
arch = "x86_64"
git-tree-sha1 = "8bc535fcdf316f09d3eb0b76b432341d7e0bf183"
os = "macos"

    [[Clang_assert.download]]
    sha256 = "332c3cfa0f18d2e52d5bdef3bfe999445d70b1067b42158f9f4f232355053752"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+1/Clang_assert.v13.0.1.x86_64-apple-darwin.tar.gz"
[[Clang_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "453f2180dce89d21dc7cee5865d1243084f8b4ab"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "a43644d1a2e22c0c567a17688d1889425ee763eb47b3ff7a781414d32eed4642"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+1/Clang_assert.v13.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[Clang_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "02dc1b2250c8ed78da9050af8b503733b3db9d5b"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "696f50b9ac92230e4f63fe98f82f710520a4a354bc8dc876f6ac33b8d90aeb4b"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+1/Clang_assert.v13.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[Clang_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1bcccd064aaadbe00c61d7d6e3a56134ba34d774"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "a32bd7207b3ee3d6e29f4006cacfa1678184b0b06b4ccf1313ee75b732ecf937"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+1/Clang_assert.v13.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[Clang_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "11c71206e16e152a123cbf0854f2c4bb74fad23e"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "3b18937b9a7af6d5149d36e2d3383f06fe3ba6e2c6a01273583c6dfa0f851290"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+1/Clang_assert.v13.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[Clang_assert]]
arch = "x86_64"
git-tree-sha1 = "d6239363bb2385eb1af590b7d6c7628ffdb11647"
os = "freebsd"

    [[Clang_assert.download]]
    sha256 = "74aa1c544586234c5fb045a38001d006e6bcc5621a7aad8d12610471b3c72d43"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+1/Clang_assert.v13.0.1.x86_64-unknown-freebsd.tar.gz"
[[Clang_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "62ddc4acaf7368427beaf9ab630c54fe7a01cc88"
os = "windows"

    [[Clang_assert.download]]
    sha256 = "e86493fe1d5e4d87e5ceac745d718b487c65ed0a5c3bc5eb611b0030ba87aeb3"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+1/Clang_assert.v13.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[Clang_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "56cb04e354eb6073f835b781cfc75c1d3d521956"
os = "windows"

    [[Clang_assert.download]]
    sha256 = "6508133a6693557c1c263194ef098c95c16c79b9b2393ef05cd59d47ece30c1f"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+1/Clang_assert.v13.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
