[[Clang_assert]]
arch = "aarch64"
git-tree-sha1 = "a44d5365488731db57f8daf590419ea2b7aba7ed"
os = "macos"

    [[Clang_assert.download]]
    sha256 = "76388cffedcee21f157cee569c40105099a7a63c6d42be3aa08d35298bd082db"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.0+2/Clang_assert.v13.0.0.aarch64-apple-darwin.tar.gz"
[[Clang_assert]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e0a3af02b9883e0f3513d6e350852289cbdd6920"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "0a10ddb9ccd20291996190d7bbe6683823dbff5e26283de8d7dbbc668c749d7a"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.0+2/Clang_assert.v13.0.0.aarch64-linux-gnu-cxx03.tar.gz"
[[Clang_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "98feffa4885adfc590c122f85b960cf40d2f8bca"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "e1e31b2072ef4b790f31a506f2634a0116b206a0d7b55c65ec680d27d65ffb1c"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.0+2/Clang_assert.v13.0.0.aarch64-linux-gnu-cxx11.tar.gz"
[[Clang_assert]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "66cb49b5e2380b25679595b6f13a81b3c51739f6"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "e64b754939d426784c87ccf206c3d45c1b23928d5ad4beeb7ce18487d121db44"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.0+2/Clang_assert.v13.0.0.aarch64-linux-musl-cxx03.tar.gz"
[[Clang_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "454a5f28578d2c4093deaf31124ef93e68e44520"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "bb1c0aa361af623c61a2c31d0bad9d749bd6ec3337ff4e38345ae70956c7459c"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.0+2/Clang_assert.v13.0.0.aarch64-linux-musl-cxx11.tar.gz"
[[Clang_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "027e837669252fa3715f337131824d2f6aaac7d2"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "a998c2f98cbff0f3cd7ef9f9faab2785e98dba302aaa656433b7db12c5e14e5d"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.0+2/Clang_assert.v13.0.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[Clang_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "efb39bdc18135cc2a2a156b45851316e6a07ef6a"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "cf5f9efcb650b41b12c6856332dc3e544d14d5b43b81188bc3c312ed9e63b247"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.0+2/Clang_assert.v13.0.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[Clang_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a1c64ce86abcbe1cae9e331e12f29be57085236a"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "27261342487d867ac7fcd39aead32390e10a2427ad8568ddd3f50b9dcae34bf5"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.0+2/Clang_assert.v13.0.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[Clang_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5a10c027b55a247ca0030cfb94f98292090ad712"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "f4af5d28b8f47553750f1cf52680f538f9dd3de32963f41faae7bc48754536f9"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.0+2/Clang_assert.v13.0.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[Clang_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a9ac381adea9c62231bc58b492a54f4f1828e3bb"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "2d004e664cb176bc8cfeee0ec2d145ee919756f9072d452336144f0e55197832"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.0+2/Clang_assert.v13.0.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Clang_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "af6fe7a2c40ab6541eb1b0d1d42cd042db2c7941"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "76c297411e59abe6cd6915f715939abaaf9f0401d567ab6f856b4f9ab23c48ae"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.0+2/Clang_assert.v13.0.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Clang_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2d47fa13f0d54f8826c84b8a1d79c32a2d6c5a8d"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "06e5d9ca992294cc67b8debdd920e6713ac9c3379b40dc9899010723856c30b4"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.0+2/Clang_assert.v13.0.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Clang_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d25aa454b01d0193ff02cc9cc46512b1b454012f"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "336bb919f08feaf3d0879f89907d1016db0ec3d91521343c91c4616a42999479"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.0+2/Clang_assert.v13.0.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Clang_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1427e0e6a3ce9a02baaa9909546bc5ae1571dded"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "a188024d327be2a02e45c5575e080933a0dd73091af7a95d4254182e595f5956"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.0+2/Clang_assert.v13.0.0.i686-linux-gnu-cxx03.tar.gz"
[[Clang_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7e43dd052abf79dd3e8d6a53c6be97eff0d101c9"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "8b78f0bba4ad3ccb9978e22b32123e85f932a0d17552275cc83d010efd7a2312"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.0+2/Clang_assert.v13.0.0.i686-linux-gnu-cxx11.tar.gz"
[[Clang_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2afb5a92943bb637f7495055bdc01d222a8daae0"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "6e167beb870eb6229dce74e42c92ed64b0a9159876994185700a4c0ec7badf2b"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.0+2/Clang_assert.v13.0.0.i686-linux-musl-cxx03.tar.gz"
[[Clang_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "93aa9272f775a0484741e77ec8a8602c75d337d4"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "e6ab093418a8bf6983c89c3010c4eaf9d5f7d28738276904853da9dce342ffab"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.0+2/Clang_assert.v13.0.0.i686-linux-musl-cxx11.tar.gz"
[[Clang_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1ebb044d72da64da3419bddc69634c23b42cf160"
os = "windows"

    [[Clang_assert.download]]
    sha256 = "1cea324fbd9b0ff01b3978f256cc341366d42c4e66a46eb50dc0adc4e4d97f31"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.0+2/Clang_assert.v13.0.0.i686-w64-mingw32-cxx03.tar.gz"
[[Clang_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c541f3b0850bf50dc777c4f66bf44e67cafafe43"
os = "windows"

    [[Clang_assert.download]]
    sha256 = "0b47c33e1c0aca7f5311a83d9c7baf39a4ee9dfaf42ad6a748dbbd1b08bdfcfb"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.0+2/Clang_assert.v13.0.0.i686-w64-mingw32-cxx11.tar.gz"
[[Clang_assert]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "25855d71b6e61716ca990e2e5f812e968b0d1912"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "2816dc36c13042a0dcb5bbedb40971d75aa7def1354ab422b91c2008dc5ed6ea"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.0+2/Clang_assert.v13.0.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Clang_assert]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c684d1c385fa6356af5410d5adf8d205e4c6aba7"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "2badb05a572a8bb416a44a33e560ba73cd348d229840cc2ca9a2118456ff2f0e"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.0+2/Clang_assert.v13.0.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Clang_assert]]
arch = "x86_64"
git-tree-sha1 = "00eab77c218daecd6e79cc2c4c6774ff9a4dbaca"
os = "macos"

    [[Clang_assert.download]]
    sha256 = "b33495b98775fc8c8b8e1dad700353c08461d011ea7f7149cad2d288b67b80ae"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.0+2/Clang_assert.v13.0.0.x86_64-apple-darwin.tar.gz"
[[Clang_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6345769725a128e28337950aa81b6ce637da58d8"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "6c615ba542632f7b0ed58ca365c06b069559090237dc107db54b681396b1d1d8"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.0+2/Clang_assert.v13.0.0.x86_64-linux-gnu-cxx03.tar.gz"
[[Clang_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f2c0d0709c39d7f7806b8f78c817b3321e1d8bae"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "9e4ccff298b1b1fb1fc0a725463cf5619e2343b992e8a6b40b4bc1afbdeb982b"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.0+2/Clang_assert.v13.0.0.x86_64-linux-gnu-cxx11.tar.gz"
[[Clang_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "379ba1baeb2b34dc4c185004bebe89b36149afde"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "8d04b4454dfce64cc86aa0d10ddbb5165cd20090c93a7578bc8a6833ea069f27"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.0+2/Clang_assert.v13.0.0.x86_64-linux-musl-cxx03.tar.gz"
[[Clang_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0a5fcc1a9f0701bfb41ac2676c7afa5026d75741"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "0a5763f24f0508e141a32b555d2de1da537f5d2f1497472e4ecd4a806e036d8d"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.0+2/Clang_assert.v13.0.0.x86_64-linux-musl-cxx11.tar.gz"
[[Clang_assert]]
arch = "x86_64"
git-tree-sha1 = "9853cef088bfb42fb48f3e80295c8a40b341bf02"
os = "freebsd"

    [[Clang_assert.download]]
    sha256 = "1e644b151a0d9cbaeae7664a4bfc928affaaaee3f5d5005321441f0e1c746ff9"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.0+2/Clang_assert.v13.0.0.x86_64-unknown-freebsd.tar.gz"
[[Clang_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f0eb96309e066fcf2373cdd162b4d72b6bc785a2"
os = "windows"

    [[Clang_assert.download]]
    sha256 = "25b71713eccdac231124a9f653f80d45408f8e44158a4fbc3c7d885d03256863"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.0+2/Clang_assert.v13.0.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[Clang_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "dafac10dcd4def182dbb96ba528fb6960351ec74"
os = "windows"

    [[Clang_assert.download]]
    sha256 = "7469dfe295b3e648ab106e3dc8b308e285c38e0222921197fd69e17d53660abd"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.0+2/Clang_assert.v13.0.0.x86_64-w64-mingw32-cxx11.tar.gz"
