[[Clang_assert]]
arch = "aarch64"
git-tree-sha1 = "f0a0c88c93eb04da62c563eeba0eb93c7c680aed"
os = "macos"

    [[Clang_assert.download]]
    sha256 = "2b3a330bdad9b6bb0a6300cc56f147d3ce5c6715660b299ef2fbd4837e159cc0"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+0/Clang_assert.v13.0.1.aarch64-apple-darwin.tar.gz"
[[Clang_assert]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2e47b624f815ce9fc3889c791a9d57c2730d6ef5"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "0f5e50e2795611eed2d6cdc3db53acb4fb62deca4f405406c7986623473a050a"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+0/Clang_assert.v13.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[Clang_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a438862a0c304fd10be4c7f7eac98229e91fc5e3"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "48f402e5b73d6c3b30d5927bfb9557f2488a90e1da5da08780b2b21ee8d250d4"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+0/Clang_assert.v13.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[Clang_assert]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "444aba035bea038a99aab5a88ec98af5a9ce34a0"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "359c8309229c05fa344b181bd354c03727f3bd4f9603ac62f4708981a87451da"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+0/Clang_assert.v13.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[Clang_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2a6bdb4c85cb17abb25d1fe2445250a801c9eb34"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "99225859f54863f91981065517a1f23d7c0a35196db796f9cd7eb50e5799e14d"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+0/Clang_assert.v13.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[Clang_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7b292ac7e0a0aa8a060e22791387932ae2d7e35e"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "b5d94c542a5f4a0cf616c8f69b453c570b157e75e02233cb091548edb56a2eb1"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+0/Clang_assert.v13.0.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[Clang_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "662c38e66acd40fcd3a669fc864b1c1002895597"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "84133babbb5ca5c3e0580269ff16e243b0f7efe6b1b09ae79f4b68a53569ef25"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+0/Clang_assert.v13.0.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[Clang_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "fc731266277f4bb72260bf8fbd48e6204a14f146"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "ad6123e67cb7d301de8ccc39081cb03acaf5b5899d9a314a857d8dc422aaa687"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+0/Clang_assert.v13.0.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[Clang_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d44cd72505990d2efece4a38720d20e529c1ba5a"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "3c5d1d7728c9ab4f6294d97cdf2d27e5a6e1b0ab926f2ea559fb4357674342d1"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+0/Clang_assert.v13.0.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[Clang_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "05aa2fab5fe31a9c55ab204a4ea11a5cc639b7f3"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "52f2cef96d29909640695ae1adde3c19b1a7717a69a4486320a8e69b0bb57cfc"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+0/Clang_assert.v13.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Clang_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c06f7ca02c7d6f8bf140af29bd272f934e6263a3"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "3087f01f9044e5b88fdc656ffcfa53b808134d74a7d1942436341590bc8fdd53"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+0/Clang_assert.v13.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Clang_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7d9e135a952b325555875377c3e9bee2678e7a3f"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "2c362901de3cbe093b82e2ab3f6516608778cd306db44dfb823ed6be834a2bc8"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+0/Clang_assert.v13.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Clang_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7caeee626ec6e1a1f7a964335df016811e7f2a43"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "f2b8094289ecfb568aa665567b09b24eb1116316e3707993d9a43d8cb0399bb0"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+0/Clang_assert.v13.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Clang_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4749db12dc0eed457e2d0f05ed87d12ac7a17e52"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "2e11de2bef5db064cb00f2d753dab14473ac74040011d60c25612ee71d07c68a"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+0/Clang_assert.v13.0.1.i686-linux-gnu-cxx03.tar.gz"
[[Clang_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b15bcee16a57e0d9a42741dbfcaa2e4ddbce13cc"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "7eb405afec095588c1851e60527d1fdaabd8cda895c0de425135ee0d4635b13d"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+0/Clang_assert.v13.0.1.i686-linux-gnu-cxx11.tar.gz"
[[Clang_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "99497cc4e94ab936b037bf4ca7dcc9238fe4e8f7"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "08f92d0726f6f84a24132d3d7d7f84fa091f80d4819f66653f04020c00cceca4"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+0/Clang_assert.v13.0.1.i686-linux-musl-cxx03.tar.gz"
[[Clang_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d7189595f3f221257233639095b3525c4be1b2fa"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "2f5cc5d77092417a672fd410fb56671d4186cc7c732a7556be2d3702dd733846"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+0/Clang_assert.v13.0.1.i686-linux-musl-cxx11.tar.gz"
[[Clang_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f34e7980b78516f41f35e920910629415113503a"
os = "windows"

    [[Clang_assert.download]]
    sha256 = "fa4f910528f1d2d2e9dda75eb8fb884de3df85faf72054d08d33a6d99a74ea03"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+0/Clang_assert.v13.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[Clang_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "72bfdfbd3b2e4f38599195e50c452515191727a3"
os = "windows"

    [[Clang_assert.download]]
    sha256 = "fc73aef661708cc39df937401dbd57e1e98b3728ca0a16a5d4db9a0354cc00cc"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+0/Clang_assert.v13.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[Clang_assert]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "7aa666fc943a077acf37d479941c34ecb55ccc11"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "06cffc37074f0c5adfa33c7ddd6ff9d407139a4bcc5c173f81336146e4812804"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+0/Clang_assert.v13.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Clang_assert]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c94ab361a5cb62e427c2edc8ef09e6e3ae29ac52"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "d9741c55b694360cb5abb27b96e65f2429a46d497ca0ec41c3ba093e84d58a8a"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+0/Clang_assert.v13.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Clang_assert]]
arch = "x86_64"
git-tree-sha1 = "55b78691328aea2b2ab3d0892a3def0192fde176"
os = "macos"

    [[Clang_assert.download]]
    sha256 = "45b5c6936fc4e9a6e545c9ecab9ee3051fb06f0ac46c25dbbd15b89e9bf5b6b5"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+0/Clang_assert.v13.0.1.x86_64-apple-darwin.tar.gz"
[[Clang_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a2addc269ae2593c1c5e7e35c52225351f3a5cb4"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "c54bd3236141e9791d3f78b25aa46f802c960951c8bcc87d777d307560234101"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+0/Clang_assert.v13.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[Clang_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f644ef8aaedce5a35388bd8e096b7bfc514fd4f8"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "50b693bef23dedfb9f8bb3ed01f3edc026c6db0e96b6171daa84d3b482213a32"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+0/Clang_assert.v13.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[Clang_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cfe8bcd75aa809f9250df90a2e73e13a2a67501f"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "a7b6719a6cd7b9b14e21343bf87c40b2e58bd2d115937b46feffe4a21ad90052"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+0/Clang_assert.v13.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[Clang_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0a4c79d1fb6b64a196827bffd9dbb92ceda1826a"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "aa3dc9347fc85e9d59da3a59e9b0863c86e8ed33478745179236c7ff5ff3be6b"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+0/Clang_assert.v13.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[Clang_assert]]
arch = "x86_64"
git-tree-sha1 = "780f7c0946bac405b2ac53a661fa2b84a1830563"
os = "freebsd"

    [[Clang_assert.download]]
    sha256 = "72981e3e22d003e442b895318686801f3129c80b70d788723137fb23426bc8b3"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+0/Clang_assert.v13.0.1.x86_64-unknown-freebsd.tar.gz"
[[Clang_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "afbb777e7fb47bb75264d0c53475e0c10d831bf1"
os = "windows"

    [[Clang_assert.download]]
    sha256 = "1a884f6614753711848c371d7e179b8f6b59afdcc975a26e9a678de804c74bbb"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+0/Clang_assert.v13.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[Clang_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8a36161bc5da81d538b3212b1f7baeaa7bc61d99"
os = "windows"

    [[Clang_assert.download]]
    sha256 = "3190fb4886d4399506aea7029cf7abc863a9cf91a21fe82c90daa3d1dbd144e6"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+0/Clang_assert.v13.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
