[[Clang_assert]]
arch = "aarch64"
git-tree-sha1 = "8594de3ec4307ce9cbfed015ea25030984bcc73d"
os = "macos"

    [[Clang_assert.download]]
    sha256 = "d4bb8852e3304867bb705eda02bb25c1411372546be252842fe3760c06630a9a"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.0+0/Clang_assert.v12.0.0.aarch64-apple-darwin.tar.gz"
[[Clang_assert]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "eda1ccdd0eba0d95ef86edad86beab994b60a1c8"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "2d5425c2d713ecf58ca88a00268cda6a09b3af0df6c8a2a344c8c6a54aec1864"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.0+0/Clang_assert.v12.0.0.aarch64-linux-gnu-cxx03.tar.gz"
[[Clang_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8e40cd0931a6931097954932ffa055d24b80a1fe"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "7e23a1d03e84db3271a3feaa2909b3ad88b39507c0b643ab1a07c4972c373a5a"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.0+0/Clang_assert.v12.0.0.aarch64-linux-gnu-cxx11.tar.gz"
[[Clang_assert]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b027832636232a6df9c939fc838efde13306f539"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "7f563024fa1d5b1d6f2d46f7e12951e0e72f6ecb9a8da231f4ca1bd2bfa0e6d5"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.0+0/Clang_assert.v12.0.0.aarch64-linux-musl-cxx03.tar.gz"
[[Clang_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4afeda615b68e232d403912fd7d29229b77f6547"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "98e34b046ff8f8686883a7d33d4b5212c30d6726cce8dccde51aff09ec6d5e1a"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.0+0/Clang_assert.v12.0.0.aarch64-linux-musl-cxx11.tar.gz"
[[Clang_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5ac0362d8dbfdd860b706e45d27b6a41b0d8992a"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "3798c6acdb9792d985293ad0363e0aedcbd8b6dadb6f748a3dc542e9f3022e6c"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.0+0/Clang_assert.v12.0.0.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[Clang_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9fb69609e98a645a4054ee532f1130c9cf0f6d78"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "43e8f6369847710d4ddefc5cfa7dd16a4b59780bce7b6c907b83eeb0b54fb3eb"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.0+0/Clang_assert.v12.0.0.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[Clang_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a6a629f8cda3ab751da07e41d727a79169f23067"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "2e98ceb403444d60a40d7676e94945630cbd410225cb0c94259e5a4d080c0b66"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.0+0/Clang_assert.v12.0.0.armv6l-linux-musleabihf-cxx03.tar.gz"
[[Clang_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ce68810be80326af7ba323786f54d1bd947d223e"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "efea82f4493876182cf2f47e04c85b4c32de23038e3d77ff2f5185f4fee4be76"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.0+0/Clang_assert.v12.0.0.armv6l-linux-musleabihf-cxx11.tar.gz"
[[Clang_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "56fb85779c4188552eec13529d51463aec6282bf"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "6f4ba0cc4a909a4df541c76f2b7668e80ee2c53a9c47e1b22e31d0e6149de310"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.0+0/Clang_assert.v12.0.0.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Clang_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ba0502ac66cf2127443a5c19252fa0080e3a8c1e"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "383bac82fdaf5c40a389dbc0cc68b9031ca1bec7aa25c5ad920afe607ed304b1"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.0+0/Clang_assert.v12.0.0.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Clang_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6942331d64a405c1e70cfd138257a6cc1665642d"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "234646ad147cc00ec136197631664b2879dfa7c6ea974633cac3814d21f59655"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.0+0/Clang_assert.v12.0.0.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Clang_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1e9fa100633dd5fc184965cdcd912c7b12496413"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "fe0361c59189e600108d41db155641d5ff45b2fdd4a31be687d2bd7bff51b54e"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.0+0/Clang_assert.v12.0.0.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Clang_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cbfcc9012cdec18bbdbb62870c39bd953f72117b"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "8a48a79b34f47aea0c67a34f52756a812efa21c49ef6c477d4968ab3c8385c5a"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.0+0/Clang_assert.v12.0.0.i686-linux-gnu-cxx03.tar.gz"
[[Clang_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a4bea78b6e05dc424aa2e07c9a87fb7a37a9559f"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "9af23dfe3a2707537adab58083d2f8d306fff7699557a6ef81ca4bf94688351c"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.0+0/Clang_assert.v12.0.0.i686-linux-gnu-cxx11.tar.gz"
[[Clang_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "80a47a8c5daeb5c800f82c9a7e66eb336ed35013"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "37df5ca8a71c43d107d764848e9701367b8bbd6ef523e330d7426ba886cc2aec"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.0+0/Clang_assert.v12.0.0.i686-linux-musl-cxx03.tar.gz"
[[Clang_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3339fdbc9a104a498820187af11972720073a554"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "92e7b8222cdecf71f745ef0baa832a681222ea5cccab4c3e62b8fc88b9079776"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.0+0/Clang_assert.v12.0.0.i686-linux-musl-cxx11.tar.gz"
[[Clang_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "98b496c96596355c17e24aa9d140c439d336f3e1"
os = "windows"

    [[Clang_assert.download]]
    sha256 = "e7e8aff830c72c5b6a017c98c3d11b24791c889a6fdcd924484b8f8cf77e274e"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.0+0/Clang_assert.v12.0.0.i686-w64-mingw32-cxx03.tar.gz"
[[Clang_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c6ec1c3ec49b62679ed39f5aa9c88c72ce27f7e9"
os = "windows"

    [[Clang_assert.download]]
    sha256 = "ef97f34d760ac99e24fc18e74220fa2b3798b63c882371a44070fec567c688de"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.0+0/Clang_assert.v12.0.0.i686-w64-mingw32-cxx11.tar.gz"
[[Clang_assert]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1185932c1f65b277addf1e30e73db9e4d405a048"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "5b14da759f1d32c8d45820e6906b9440422e38294c121b6b09ff3bb724ed4313"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.0+0/Clang_assert.v12.0.0.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Clang_assert]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "afbcee00abda43941fcae103f88f483b5855f831"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "08948b3a03c0a7054b7a917f54c20bf8b1e2824983b5e3aebf813d8f4f909475"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.0+0/Clang_assert.v12.0.0.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Clang_assert]]
arch = "x86_64"
git-tree-sha1 = "42e4eb09afea17c818919451fbba0182921d19c7"
os = "macos"

    [[Clang_assert.download]]
    sha256 = "26cf17359e9dc9cc536a97288f9d04b24c4bf7c7d06cb5f817539f681af1f3af"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.0+0/Clang_assert.v12.0.0.x86_64-apple-darwin.tar.gz"
[[Clang_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ee276b326fe47da796fa28b9f18525ca3e07fdca"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "9efe28c2298e2f741d3c93c149ee851823fe9e89d0b17d6cd5bdc732a4822fa0"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.0+0/Clang_assert.v12.0.0.x86_64-linux-gnu-cxx03.tar.gz"
[[Clang_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ef852f8116c02997c2e921608e333f332bbb606d"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "da4af3de07b9d133b1dc2ae469562237bedd3d8d4b812471ebdcdf741595d10d"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.0+0/Clang_assert.v12.0.0.x86_64-linux-gnu-cxx11.tar.gz"
[[Clang_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "83d92290ac5c39707d9069d9b6d5b21ac1db1879"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "9667c48c2fb553345d7609f62bf5910bf317986d812a0cc0113ce7b5ff2cf51b"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.0+0/Clang_assert.v12.0.0.x86_64-linux-musl-cxx03.tar.gz"
[[Clang_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "bf1a08d8cd6452c5515d5c22fb91419db9115798"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "16d70446956210f028160d40316502d89f2cec6a9cae2bc3d9980271be58e481"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.0+0/Clang_assert.v12.0.0.x86_64-linux-musl-cxx11.tar.gz"
[[Clang_assert]]
arch = "x86_64"
git-tree-sha1 = "7bcec37ee350e7d50de33a712d3235ad500809d0"
os = "freebsd"

    [[Clang_assert.download]]
    sha256 = "b0e6e61b63bdddb9bd014adb3f230924321655f7c0ec3ed97cfd1cbf043a781c"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.0+0/Clang_assert.v12.0.0.x86_64-unknown-freebsd.tar.gz"
[[Clang_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c174c275a00b8a0e43505e1c3531ab62a87e0ed1"
os = "windows"

    [[Clang_assert.download]]
    sha256 = "c7fa3a669b8d192d5ad5748361e72bb2cbb10a613e026fdc8d683e862bb87d85"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.0+0/Clang_assert.v12.0.0.x86_64-w64-mingw32-cxx03.tar.gz"
[[Clang_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "97e3ba20ca92a756ef342c8d234193f25445320c"
os = "windows"

    [[Clang_assert.download]]
    sha256 = "d49d40f91c5a8cf887220a0db5460d1573ce0b298ce018d8dc38152b325b44ee"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.0+0/Clang_assert.v12.0.0.x86_64-w64-mingw32-cxx11.tar.gz"
