[[Clang_assert]]
arch = "aarch64"
git-tree-sha1 = "5218e8884bf587ef4d1e4b35aede886e4e353fc3"
os = "macos"

    [[Clang_assert.download]]
    sha256 = "7d2a19c3fe94f517ad40a7e1c3e0a782213f97381086d6ce249a90874730739a"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v11.0.1+3/Clang_assert.v11.0.1.aarch64-apple-darwin.tar.gz"
[[Clang_assert]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b02aab3b77f0580220efa782969b77f5af6e1638"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "8c7f4383a005c47219bef5ab3a882beeae7a085964e4b2996daaaaba184c2306"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v11.0.1+3/Clang_assert.v11.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[Clang_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "b01a422115b4d2e63cffcca09a9775c47aabede9"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "76546fe45ed39fcc1adbb1b34cd0f4d655ed1cdafdc08fdc75f9b1f0649e027d"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v11.0.1+3/Clang_assert.v11.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[Clang_assert]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bd01f2ab2cc883346f9f6b533cc3fa30e8b420e4"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "cf2dba35fec4b218ff8cd8b4169a2dfbc1ecce2b87579e9a53364d0aa582c419"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v11.0.1+3/Clang_assert.v11.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[Clang_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1a3cb05cb71d8d2890f99cac3b637c3d0ce63866"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "04078d2a5661c6d3c1d2a010b02318473b6faa6584a0c504b35cda949aa2d277"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v11.0.1+3/Clang_assert.v11.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[Clang_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "91ec19d9e5424d3081add0deba26212a7454800b"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "de308acfa5ec0ea9c461e4a7c85ae02aaa8dab395a9c716337489855f9ea795b"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v11.0.1+3/Clang_assert.v11.0.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[Clang_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "db054ec5289398bb537dfd25482a3cb761dafbb9"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "ff1929e62966468c03e1cb46a1bea360a703526fc234d29021465408ef62c9e0"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v11.0.1+3/Clang_assert.v11.0.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[Clang_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a7cae913eede17d4ab126319e460d65482493114"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "830aa8b2dd346eb8585d1f27ea3339bd57db7ca90288e4b47b3c5d94115adf0b"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v11.0.1+3/Clang_assert.v11.0.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[Clang_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "5c556dd047e05641e55f33792afbeaa827f844fa"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "b754fb4666269734470c75138d3e2cd655c3bfb7520ed4b36be0029f34f9e2eb"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v11.0.1+3/Clang_assert.v11.0.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[Clang_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1efbbf2bcddd30c625bc08f2e4e6547329125e5e"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "ef43aaf45c126f237f9a3ae579cbcf791784bd8d2f882cc97e53a1c67593ec21"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v11.0.1+3/Clang_assert.v11.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Clang_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "d650303462ecc5a4d003a970d6bb0a6d9eda39a1"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "4f8145fdb815133a2d2278e31e6c18328995609d92a794880e0aa8281d19b2ce"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v11.0.1+3/Clang_assert.v11.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Clang_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "670ce9e3868b1f770c96aec1c429bee254020512"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "28e52d3447f3783a4e2e77bb14f640f0b5bb7e4c9f29a7d0894b401f85694810"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v11.0.1+3/Clang_assert.v11.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Clang_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "38fc535681991fa31833012735702c4047393f34"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "fb4d1b31a742a67cbab663bf7158f6853ebb1b57f737c0021aa3feea29dbd910"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v11.0.1+3/Clang_assert.v11.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Clang_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d5d7ddc79e79c0e18a2fc8ba3e84eacf653b3a2c"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "61be2861ce12ee62ba797662632da2a05b0af51289e7ffd34bbe43a6b391c5d4"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v11.0.1+3/Clang_assert.v11.0.1.i686-linux-gnu-cxx03.tar.gz"
[[Clang_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4fae9e78e76c92a716d1b25c362f3f6e177993fb"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "2e33729858cc9234b4f0d5ae3af947d174831932c3db5ee972e916fa833f6bd0"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v11.0.1+3/Clang_assert.v11.0.1.i686-linux-gnu-cxx11.tar.gz"
[[Clang_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bde1859f2ce49f4956e828e9b815cea8bc8fd247"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "4b1424fa325d24f4ff0ad2b45d620dad311d27bf9f14e7092cc277a90e4c759e"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v11.0.1+3/Clang_assert.v11.0.1.i686-linux-musl-cxx03.tar.gz"
[[Clang_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "29c2326735c9bc019fb8f890ffc025f873db4c72"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "69c975122e712c71095e24e6cf92dad13bab48a1e40565804a11e99748efa8ab"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v11.0.1+3/Clang_assert.v11.0.1.i686-linux-musl-cxx11.tar.gz"
[[Clang_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8e657246253e655a653ddd53356ff8319b2f0fa6"
os = "windows"

    [[Clang_assert.download]]
    sha256 = "c990d66ea96cbd77458631f60dd68fd82f95e14d79e31e10911b50041d4b97d4"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v11.0.1+3/Clang_assert.v11.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[Clang_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6bae82156a1e8a3e4b6d7a7b715562592eaa1226"
os = "windows"

    [[Clang_assert.download]]
    sha256 = "a4eb73c9a28876dc5e685bc2725684c5a09b74fc01efa5859d6f10511aef3ff2"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v11.0.1+3/Clang_assert.v11.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[Clang_assert]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "b56f2cd89088625868c9ff750d0cc26a7ba668f7"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "c373c3e88092322a08cf253740e84af233ab7bb70b23f20b54ba37b1fe4b9ec8"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v11.0.1+3/Clang_assert.v11.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Clang_assert]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2e98ba14bd5647ff60fd6554d4116d6085a60d1a"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "5aa37d926cba4b21c6ba32c3fc794ae9dd8b053fd5d6e120f371ffefdea61ff3"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v11.0.1+3/Clang_assert.v11.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Clang_assert]]
arch = "x86_64"
git-tree-sha1 = "68f1248fad9f3d537f0d86f0a5fcaac1483c532b"
os = "macos"

    [[Clang_assert.download]]
    sha256 = "6b0fbf22755b8df2f4edda8a8ec6812218b0d569b920a5904bc3f60673ca1fca"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v11.0.1+3/Clang_assert.v11.0.1.x86_64-apple-darwin.tar.gz"
[[Clang_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5c7f36352fc634abb6393ff20368cf80d08668b1"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "1bd4b3b1e83375dd6a9b86a9dfdb048945bbf7239f7133de9e7781b5366bb6bf"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v11.0.1+3/Clang_assert.v11.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[Clang_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "12e39d2115e08928ed32e1aece6b8f0a9834c328"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "f90cdecead4f3db5901715f005593db42d2667c540bf4a3c08bca85eb63cb22a"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v11.0.1+3/Clang_assert.v11.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[Clang_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "889e26e0e6a47eb7a3fc1b4403b9774a65f56fce"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "810e7bd21d41402e86f9079d2c4cad4ada7937ccf41afbfe7cff1f0157fbd85d"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v11.0.1+3/Clang_assert.v11.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[Clang_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "ce63ffa3d153eb0e9c6e1fe9c9e8786ebba52205"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "c909535541128ee75865ca6532132ab16e0fa320876acaad7a16c4cf0f252f1a"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v11.0.1+3/Clang_assert.v11.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[Clang_assert]]
arch = "x86_64"
git-tree-sha1 = "0afb78a7bb56f5bfdbd63c065ea743046b550c31"
os = "freebsd"

    [[Clang_assert.download]]
    sha256 = "488574adc4aeea13a4d17b203d31ff601646537a3196485255436b647983c5e6"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v11.0.1+3/Clang_assert.v11.0.1.x86_64-unknown-freebsd.tar.gz"
[[Clang_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "20672e4402759ae31b81430b4cc476810b77270d"
os = "windows"

    [[Clang_assert.download]]
    sha256 = "1492de371aac0d5c2a3ab1dbdb1cf2793ba80d047513c0024ba471ac9c70b54b"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v11.0.1+3/Clang_assert.v11.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[Clang_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c5faf003fe4a8913d1212ea56e298dd4d96e7870"
os = "windows"

    [[Clang_assert.download]]
    sha256 = "febf346587fca6b8c0e745a431ef3fa743d47ac13a926eb39a177d374b3b2cbe"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v11.0.1+3/Clang_assert.v11.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
