[[Clang_assert]]
arch = "aarch64"
git-tree-sha1 = "8f1d5275af6268cc3b43619664980ae24e07f838"
os = "macos"

    [[Clang_assert.download]]
    sha256 = "a8a4942423f336615b91c7da96b6f0f98e5dbd9b1264b54d1dd6de4cfa7652aa"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+1/Clang_assert.v12.0.1.aarch64-apple-darwin.tar.gz"
[[Clang_assert]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "cc2b5fc438b3af4c86bcda5207b34b9e3f435a09"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "fb9adbb5c3000f8ea5678cbcbed9d116eb9c40275376d42366c75c90c78ccf94"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+1/Clang_assert.v12.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[Clang_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "11862a8b50b69f4e94fed4faaffec944dd99b851"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "a94cab599a1c5921660338a2f668efceaa2ccd0d4d9abe3458c54d25807448bb"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+1/Clang_assert.v12.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[Clang_assert]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2b2c28739262e888f60248090a4ffff10381c650"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "90e14a9da952bdc0cd4ca4bad2b0cb68920b96d1eff7e1ff4d11ec518cd2331f"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+1/Clang_assert.v12.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[Clang_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "045786b41d2a16e2a8b0e2cce5f82e1e94d60bfe"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "845f8fdbdb33bfd65209acd8ae8210f01039edf6a826a7b279cca84ee8cd76ad"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+1/Clang_assert.v12.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[Clang_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "d279186df5389ce6223fd154d240b4fb55384247"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "7f76dcd017106e1d8a52d086c23441200d9d413790059805b04d465c9fc2aa4c"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+1/Clang_assert.v12.0.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[Clang_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "572b30f556917c9cc88bf3473fc2ffa7698f84f0"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "e8ae4cf822f9ec63b63b0c7b370dab0964f76f03b74023e68cec34068a30682d"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+1/Clang_assert.v12.0.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[Clang_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bf976598cbf90171c738ed8e93778fd4ae4c6ba9"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "592048d9781dfc97d9e8e32fe6699279618dc8b53a91a0f3df7b98aba718a455"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+1/Clang_assert.v12.0.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[Clang_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7929d5435cbffb595951b7c2000b652134819bc4"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "5b35a31cf02dd986efe5b271400bcfab05f95b68ce7cb77f93079465e27849e3"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+1/Clang_assert.v12.0.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[Clang_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "846eb1ad9495c6833db7a864c48f225387ac7d55"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "9c92351212f1a38a431f79c0c7d48993ae161927062a94f45d344270affc93ec"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+1/Clang_assert.v12.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Clang_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "44b68b1fb59591e87fc48f07696991518bdb6d31"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "847c819843b519f9ead5c741498a25e7ac571ac0457e740f23e9afcdd2195740"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+1/Clang_assert.v12.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Clang_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6b49da6de2481d08a6e91535603c1a182a5014e6"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "a0e5061a16c469b9808cc0a724a62ddae2b941c501cc9cfe1057b5fa2233484a"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+1/Clang_assert.v12.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Clang_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "683e3d1866c32bf95d9822f4eadffe18a57eeca0"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "dcd99f18373e143512cfdb719fb3161d38491ebe56547b154cfaa6e93f525752"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+1/Clang_assert.v12.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Clang_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1e929e06606d478fbab4d17f669bd0023bcf7a04"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "1c5372e90d5a20f7b9c305a2827c7ab34603f746d133d5b716138f7c9e7b11ac"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+1/Clang_assert.v12.0.1.i686-linux-gnu-cxx03.tar.gz"
[[Clang_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "824aad4d323ca95205b8733d99bc683316e7c8c3"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "d8e7d073315dadf3de2e62a6e16325302a986178ca40c030c2353086b7cad486"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+1/Clang_assert.v12.0.1.i686-linux-gnu-cxx11.tar.gz"
[[Clang_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6d01324f6f5081b8fc459680e3c0aff6c17979b1"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "b93b951946785859ff57d42224c0150671dcc136014b1a0f9a37d73510dea0a5"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+1/Clang_assert.v12.0.1.i686-linux-musl-cxx03.tar.gz"
[[Clang_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "f2221538d56e033e135249ae86c28a22463fdaa3"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "cf8254e32ad51b3034840bf6ec702fe5b87e152bccca3aa4eaa759b118c0b423"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+1/Clang_assert.v12.0.1.i686-linux-musl-cxx11.tar.gz"
[[Clang_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "bb3a81fc0e0b76fdf426ccd8b417b8e533dbdb95"
os = "windows"

    [[Clang_assert.download]]
    sha256 = "567dd9440409f0878387471acbfb256a0a1275389a60cf8bf0f63e710cb072ea"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+1/Clang_assert.v12.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[Clang_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "0208f74dd6f6a1d56fc16a8a660eff25f10460ca"
os = "windows"

    [[Clang_assert.download]]
    sha256 = "4a668ac504116aacfdab110fe3e8e3d010e874d591fcedbd306fccad157c5508"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+1/Clang_assert.v12.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[Clang_assert]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "a8c5bda1b7006a4bbc871f2778fc56674f5cc11b"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "65561d4795bb94e046d2c2d615965739ca6848f4382eb6fe2744e0b5c2a1224a"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+1/Clang_assert.v12.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Clang_assert]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "04efd1940a20ad53c886e7519c8e8b5ec7e01272"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "a61136d95f53d0fd5ad6ea78004c647a72b9129ac8f56c80b98dbec32f9d2d58"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+1/Clang_assert.v12.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Clang_assert]]
arch = "x86_64"
git-tree-sha1 = "381c153b23487f280a2261591e477841fe26580c"
os = "macos"

    [[Clang_assert.download]]
    sha256 = "b83058cbc48b47835bc5365ca451eb05b3800443bd31e527429b18c18c6dd6ce"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+1/Clang_assert.v12.0.1.x86_64-apple-darwin.tar.gz"
[[Clang_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e37879a6547b7ccb48670fcbfb95bf0a3e61f88f"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "af239164fd9c344fd6983ae6b7623fdd9e43787ba87aa821b012c7c937886231"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+1/Clang_assert.v12.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[Clang_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6dedee8b157c9a575d4389f26128c5d882f74a23"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "423a9385931a16e813e06b0938b55b68f8f2c5d3d3f6edcbe7a2e6b786695589"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+1/Clang_assert.v12.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[Clang_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "37eae86833676684de1c8dde3f6f4fe043d3e87b"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "7bda481777f587daf66a1a6ebc490691ff396723809926e77f7b242163967eeb"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+1/Clang_assert.v12.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[Clang_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4ef1a235a97c337d87bfae880e36d5d813a45fcd"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "42ea41a987e8e39a02bf388239fe3209507e29eef0c9b050b1d0f719dcbd2abd"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+1/Clang_assert.v12.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[Clang_assert]]
arch = "x86_64"
git-tree-sha1 = "198eb2f8d37568ef518f6130b5e5b33ef76b0761"
os = "freebsd"

    [[Clang_assert.download]]
    sha256 = "5638e4fa862de150c78bc3798a87242094efde965957e482b951f5a28c64e058"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+1/Clang_assert.v12.0.1.x86_64-unknown-freebsd.tar.gz"
[[Clang_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "9597f721b2072cb8b95d39158a2522602d664d94"
os = "windows"

    [[Clang_assert.download]]
    sha256 = "3d5426c29296e2369c539f0a7787b86322e61246fde928a1f91bc9abe7d9719b"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+1/Clang_assert.v12.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[Clang_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2815b256e495643874d54c318d9b3cbe1e761047"
os = "windows"

    [[Clang_assert.download]]
    sha256 = "5ff2c4ba3f6f56321f5b8e21899d8674ed42977d3ad2202de7c840fda2410332"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+1/Clang_assert.v12.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
