[[Clang_assert]]
arch = "aarch64"
git-tree-sha1 = "299f84c67dc442b1c1b38a55a05158f4d1a115aa"
os = "macos"

    [[Clang_assert.download]]
    sha256 = "2db61ee2f79993c695f50d8c7b6dd43f6c74e18fa0c41d10d7cd149a9e15ea50"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+1/Clang_assert.v12.0.1.aarch64-apple-darwin.tar.gz"
[[Clang_assert]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "82418bb29ca9b1000cc6889ad85d062f90913211"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "82c85f6dab384ddf70e68bf93f2738e8f66f200342ba2a9a18fbc3fb14923261"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+1/Clang_assert.v12.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[Clang_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2b73a85a4af1f00375a7b87a6f38e96292369a0f"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "da9d6536966f7202a3dc6d671beee69b41038abd169193738a5a5376c73ff46c"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+1/Clang_assert.v12.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[Clang_assert]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e48915525edc09e8a79bcc62cae21e5f5abeb5f0"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "730503b572b1a695cb04040de63f890eb2e2930cbe685a2f34f1121e5716e97b"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+1/Clang_assert.v12.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[Clang_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "32fce1b44f6554f96d1119aeeaa31e402323493f"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "c94ec76e01a50e37fd97c08fe9a2e8bda9ba9f83688025105e43b1a37c6b6324"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+1/Clang_assert.v12.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[Clang_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ab849af30458665343b42028072c82b66496f3c7"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "82f4acb38eb6f3edc551cab3f0b3c20b2e1568e0dcb1931f2b2333882f5793e6"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+1/Clang_assert.v12.0.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[Clang_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4426ab631e819202b3f3cfb8710a04b0d648b3b9"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "0c97fad23ecc70a000fccfea11b1d5139ce19834e707106b2d19cece29705451"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+1/Clang_assert.v12.0.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[Clang_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f5374dd47e6b93a7f5fd80060c7ad7a0b08afac1"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "e3b248e2a6c577d4ac5f9da3ad058e4ea0a6c5443e110e09eeb4982c047a3f48"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+1/Clang_assert.v12.0.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[Clang_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "57924a38968615e41f53e1bf78e3bf74616ee045"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "11c43fffb55b3d328208c2fcdce654e7e647402b86e95d38943bf011a833bfa6"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+1/Clang_assert.v12.0.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[Clang_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "eadf1f6a0114bb3947421d9332f872f11a22d026"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "497501c78d6a142dd1608a304cba0d9fa02e5672bb7758630311c75123bc9f2f"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+1/Clang_assert.v12.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Clang_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "43c4d2c50c75a90606657b5a8623e51cc5d11dff"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "85944cbc392b6ab9a9423000ea5e22d1a4897fe88a030c94c0e860cadbb38397"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+1/Clang_assert.v12.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Clang_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "615f48b2440c3e6eae469af72fa79b47b698ca4e"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "62f18cf85cf2f292430cb4b16c7ff6ede9a0e3c86d147aa20a0e4851b200c27f"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+1/Clang_assert.v12.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Clang_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "781d400eb5b9ee196932e87c4ec1a7666892bc64"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "4e11d2f83a09620c2a22ac5e8c1d85198f3b565ccd65420d05ea14b036929ab3"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+1/Clang_assert.v12.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Clang_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4cf362730e852d8b25eb493c698b233bc099d42d"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "a3ba1bddd011525dca1dbd008b193cd4fbfb4412839f3130aeab5ec447f3cce0"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+1/Clang_assert.v12.0.1.i686-linux-gnu-cxx03.tar.gz"
[[Clang_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "84670f6b53daea6c1d31f5d46025b8ece436ec83"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "f0058df5ae0975593b1d312d956ddea93d9e6a824381fe06450d6a086f7cf744"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+1/Clang_assert.v12.0.1.i686-linux-gnu-cxx11.tar.gz"
[[Clang_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "73de4049d56db6dd2f34d71892ed57d079f9af6d"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "246422bdd2774f0a80f37567efc22900ae18556642f05ad00497769a4634af87"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+1/Clang_assert.v12.0.1.i686-linux-musl-cxx03.tar.gz"
[[Clang_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9e73a8d07faecf63f878f28e5b7818ceb0b37286"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "13d244eb8afa43c39394830586b50e6905a8a98fbf12b5865a21b8629d9ee759"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+1/Clang_assert.v12.0.1.i686-linux-musl-cxx11.tar.gz"
[[Clang_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "6de5a65a8dbdf661871977e5a21b11a4cd2f41b5"
os = "windows"

    [[Clang_assert.download]]
    sha256 = "1ce77d72041e238966893d17aeca6d00d0683d025198bfc041dcec97960cc3fe"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+1/Clang_assert.v12.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[Clang_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4c53816cc07244249e51aa3c4f21b72a929d7e3f"
os = "windows"

    [[Clang_assert.download]]
    sha256 = "8c90eb984876d4f8b63ac5ddaf5090dcc351af77d6ff9cddade8da21c8fa36c7"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+1/Clang_assert.v12.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[Clang_assert]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "16d89ccc671072451296173d961dc8ee18f39ab9"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "20a01025f0826dbaf3e4bedbb65587e5b24cc67484f69e8b40bca6b5e01c235b"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+1/Clang_assert.v12.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Clang_assert]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "45001e476f1a2efe1a71dc56623daf7d4b99a4ef"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "3879e3ac43b321fdc33daa89b96840fa39c909abcb3e58ae33d14b759cbbde05"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+1/Clang_assert.v12.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Clang_assert]]
arch = "x86_64"
git-tree-sha1 = "8b2cecb7b2920919a4b04494a62ba4723726f63a"
os = "macos"

    [[Clang_assert.download]]
    sha256 = "c2372346b6d34fc6c16e9336f8f959f7ecafd627fcc9fb2764ba0d6a23f0dfb7"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+1/Clang_assert.v12.0.1.x86_64-apple-darwin.tar.gz"
[[Clang_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e0a7b2800df187a54c2255342fee853b9ebc2cfa"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "601fb8acb2d931a22164c9fe73ad083869af90ba8402e17666ea192dc54dec80"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+1/Clang_assert.v12.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[Clang_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c5ab3b74f03d5763be403f597c68f71ce76c6179"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "85183ebf9622317e2daed5f8b08f09b01653f1f58bbc7c201393215ccfd70731"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+1/Clang_assert.v12.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[Clang_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1aa72fca8fc2f309a2aa233c7214e1ab772169d1"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "21fd5cbeaef7ac58213cfeccf41b8e4549af55f3ee94719010192f0a1da59322"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+1/Clang_assert.v12.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[Clang_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3b931112f0fe88d28a1d561a3397ec96de6b3dab"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "396bd56da621079d62ca1cd55e9aa0531be41be3d1a70a435ae2a35b00214c35"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+1/Clang_assert.v12.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[Clang_assert]]
arch = "x86_64"
git-tree-sha1 = "332a3ff404b674265eed630ae148fb49d7419105"
os = "freebsd"

    [[Clang_assert.download]]
    sha256 = "188d7816628d955c59daa1526ce7305380addd2d28ada1423efc5f7c73481550"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+1/Clang_assert.v12.0.1.x86_64-unknown-freebsd.tar.gz"
[[Clang_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "8a6821b5bf309b78b99e26344967c83c9dd87bbd"
os = "windows"

    [[Clang_assert.download]]
    sha256 = "5be11e7d67085ecd536bcd7f580892cc861d8263d87ae1949e607472ad55dd6a"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+1/Clang_assert.v12.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[Clang_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "53dad8f4bbbc388a0b3cf30ac1b124cac92db788"
os = "windows"

    [[Clang_assert.download]]
    sha256 = "eb2779da8c6483336f023548d16c243cdb8f7a1da9f814232b991cdd946d9142"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+1/Clang_assert.v12.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
