[[Clang_assert]]
arch = "aarch64"
git-tree-sha1 = "ac4023c4398d908874e2c8bdd53554366e86ae92"
os = "macos"

    [[Clang_assert.download]]
    sha256 = "748c5a25c51d79bed5b33a33b61223ceed7f50dafcc6934eed99ade25f267943"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+2/Clang_assert.v13.0.1.aarch64-apple-darwin.tar.gz"
[[Clang_assert]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "486d0c0e8466686b17b9ee1996b7e1a740e9158f"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "f9cd4f9a4be74d62a77662e3cbf89eef06caa6f90b7d12516b5bab959d222c10"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+2/Clang_assert.v13.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[Clang_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "105fac67ce605d83a767dcca24609c9983b2299c"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "1021781065e45e195def72f0ee17e18d7379812fbdead1bc830aad1a9ed1ba4b"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+2/Clang_assert.v13.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[Clang_assert]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "658231b6b7f5bc1201b4a2a779056eff441bcfaa"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "3a292e4abc98e3f9c07138d9e0669ec06eabbc87bbccfe07c095d2af55088700"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+2/Clang_assert.v13.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[Clang_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "a628f0fa24b385b7b24946df4cbb26e84e942d4d"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "f086777a81fcbece917acd514a11ed676b0cf363a861370d6dfdf0d6c271dee8"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+2/Clang_assert.v13.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[Clang_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "5f9a5c3fe04cfbda40c65cd1825f749f1ed3dc8d"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "ae001eb677bce7ccff61eb5b22641a7da55baae49d9cd116f9d4493402fc1cf7"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+2/Clang_assert.v13.0.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[Clang_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "53242b58a80bb17c6bdac330fb94c0cefdb85581"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "552c9289a8b318610c06da4b18360e6242ab8bfa8ac5ed446e673af589acaf79"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+2/Clang_assert.v13.0.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[Clang_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1e270ff8ea0dee514dbe6baa7603756bd9c47907"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "90bd6eef6fb053aeaf2eb78894b6318aac0828fde9e74c577b72861357279aeb"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+2/Clang_assert.v13.0.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[Clang_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4be27bd30cf953f4e47abc587f94f02668c27c83"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "a6c0a8508aa171581d50c434d9ee8f8764619e95217b13b83fc7f2478773588d"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+2/Clang_assert.v13.0.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[Clang_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "13fcafc98f5755faaa07cd573c11c8bb8b7f76cb"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "73a5f921a626cf8a3e9288c7fca4c352d3be10207689c8c78659c8fd6c13b504"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+2/Clang_assert.v13.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Clang_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9534a1aeeb058f101ed35876cfb5833c7f20804f"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "cd74bb08cd3520ddf246c2b4009b42d365804289241db19fe21c12f59a976dc5"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+2/Clang_assert.v13.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Clang_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2f8ec38c1b87d021299fd9ff0670437672ccc1c1"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "3bbe108d05c52f6b8564c5ea096cfd7d6da35b98af44f47e617d7815850d35ad"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+2/Clang_assert.v13.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Clang_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c544b217d18b3dd9c8ae4b7c57c86b7fbd99b071"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "2c67cd76b891547810c44c51f6209baf2bb782f271f681a6faa0268cde07456b"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+2/Clang_assert.v13.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Clang_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "2399a8c8433648edf968f22e56bfe035d2bc0b99"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "7edd0af25f3f10d56cae989d9c14a41975e641c2db4a43fecacb5f723f47b56a"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+2/Clang_assert.v13.0.1.i686-linux-gnu-cxx03.tar.gz"
[[Clang_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "32a0edbd628c9dfeef6f136cda0183cc08a57815"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "66c98bd3a7af1046cb2fd5f42c563a7bcfb19d112a00ea41eeb15a4380759c83"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+2/Clang_assert.v13.0.1.i686-linux-gnu-cxx11.tar.gz"
[[Clang_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c400384ca7cf483ec256676396c8da1486032818"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "51e1a55177b32f412a302ab2f98fc7b3cb4636906187efa3e2b0cf415ba7e631"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+2/Clang_assert.v13.0.1.i686-linux-musl-cxx03.tar.gz"
[[Clang_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c408adfbd744d2869b71b48bc86485bd62b72d63"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "e9676764254cd3c35f0d76c74c2cdbaafa7cce8e15c0211e0693b677521829df"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+2/Clang_assert.v13.0.1.i686-linux-musl-cxx11.tar.gz"
[[Clang_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "838e4cc5b1814b8b4d25cdb86aa084c01a0ea257"
os = "windows"

    [[Clang_assert.download]]
    sha256 = "8f0f3e08ddef61e64b1aace3ce841ca9b018d3f7337b8ed1e524ec97c886e0a0"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+2/Clang_assert.v13.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[Clang_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4b04497ca3cec8645e06e9751134632fe5a50f47"
os = "windows"

    [[Clang_assert.download]]
    sha256 = "8f1025022094c1dfe5f7a41bbcea312bdcc49127ec5935e94c74030d9360da2a"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+2/Clang_assert.v13.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[Clang_assert]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e063d8172fbcb2a052a4511ecab7b194466b90fe"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "c0f91a012d6fec9c69fecd04ae0474bc928742eb5754fc0bdd1cfc6cdb22dc26"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+2/Clang_assert.v13.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Clang_assert]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7e2f47c149f9692fc35e44d70ad9978d1b547d99"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "32effde04b25ed10246e6f2574fbdef8f573f70c9ea21669389fdbd58d392b27"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+2/Clang_assert.v13.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Clang_assert]]
arch = "x86_64"
git-tree-sha1 = "904c9b2d5c18ae29c03859e6c0af8c8f8580a98a"
os = "macos"

    [[Clang_assert.download]]
    sha256 = "8efb8983c921d9c65e063fcae025b21fe3bf3aea160b8f308975c92d672236ff"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+2/Clang_assert.v13.0.1.x86_64-apple-darwin.tar.gz"
[[Clang_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "edeaba5c159f9b4a7d52deeb0d0249b617d35706"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "5850ced52b4dc77bd27f394364bf58e142d098b778db952e9143316b0905a28e"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+2/Clang_assert.v13.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[Clang_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4616db5e18ce3b7c49f172c9425d7e5b0e820282"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "4e46bfe1ceab903b8f25252c4ae55c85345da44485436fcee6c1cda98e073ef8"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+2/Clang_assert.v13.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[Clang_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "39ab84477841c518c187d8f5f28265e4fc0f5b2e"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "1b6c168611bce761a4ca9d2404e6cfa657beb590379ad59ff3bb0ccd47e57fc5"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+2/Clang_assert.v13.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[Clang_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1a6233ec1079586158b01e19396f5bb28b82aa21"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "aff3328c2a72a307aa17ef9ac6843fd1f8933771ef13d0d021472fc3ab433702"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+2/Clang_assert.v13.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[Clang_assert]]
arch = "x86_64"
git-tree-sha1 = "2c6f872f0c37821af1ea75fc740065cf59121d3e"
os = "freebsd"

    [[Clang_assert.download]]
    sha256 = "d304b8d617aab5dac3854c82a8857a351c112bf8136d5f17c298a21acfb97108"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+2/Clang_assert.v13.0.1.x86_64-unknown-freebsd.tar.gz"
[[Clang_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "c29973145e3653bdfd0aadbe6d9d6c56042eba6a"
os = "windows"

    [[Clang_assert.download]]
    sha256 = "ed670008aadabf4143d2cf28707b36f0071973d55ebaa706fad4b7bd9c476f5f"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+2/Clang_assert.v13.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[Clang_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "35571a7d538e10ae196fb666d56629516e36675f"
os = "windows"

    [[Clang_assert.download]]
    sha256 = "b4e26feffab8c0609ce1401d7e356d327593b6b6254b8cb8ddebe16f73b1f40e"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v13.0.1+2/Clang_assert.v13.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
