[[Clang_assert]]
arch = "aarch64"
git-tree-sha1 = "299f84c67dc442b1c1b38a55a05158f4d1a115aa"
os = "macos"

    [[Clang_assert.download]]
    sha256 = "2fbbc09200d62aa56c86a20b114642b469bcba1fcbe73f78644f0a58a28b1a83"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+0/Clang_assert.v12.0.1.aarch64-apple-darwin.tar.gz"
[[Clang_assert]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "82418bb29ca9b1000cc6889ad85d062f90913211"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "d82b72b384808ccebfbe41d48b02a45451744d07337dff6d888a6640653c7d07"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+0/Clang_assert.v12.0.1.aarch64-linux-gnu-cxx03.tar.gz"
[[Clang_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2b73a85a4af1f00375a7b87a6f38e96292369a0f"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "d6f22be13482c790ca6e1eb1ea250a9233755f456028726d428386fbdc813751"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+0/Clang_assert.v12.0.1.aarch64-linux-gnu-cxx11.tar.gz"
[[Clang_assert]]
arch = "aarch64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e48915525edc09e8a79bcc62cae21e5f5abeb5f0"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "31dd64a1c4901ea31cb83217843c5708192ed178799386ecc44529296fa30443"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+0/Clang_assert.v12.0.1.aarch64-linux-musl-cxx03.tar.gz"
[[Clang_assert]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "32fce1b44f6554f96d1119aeeaa31e402323493f"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "889705c1eb7a6037f24a99a0cf692c38ece0e4f25df4b4eaa9e2907a3aaa4025"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+0/Clang_assert.v12.0.1.aarch64-linux-musl-cxx11.tar.gz"
[[Clang_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "ab849af30458665343b42028072c82b66496f3c7"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "5afa4fddb017ce4bec4b9ae072f7ffc2cfad055a360bcface528cfd5dab17011"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+0/Clang_assert.v12.0.1.armv6l-linux-gnueabihf-cxx03.tar.gz"
[[Clang_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "4426ab631e819202b3f3cfb8710a04b0d648b3b9"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "561a2041867572e77e3c3f259a6e14cfe80b732a454656abcf07fc281c9ec570"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+0/Clang_assert.v12.0.1.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[Clang_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "f5374dd47e6b93a7f5fd80060c7ad7a0b08afac1"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "36739bcfdba81896b59395912adf5ac82c3479027b8b70f8c3fe85339cb8fd0a"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+0/Clang_assert.v12.0.1.armv6l-linux-musleabihf-cxx03.tar.gz"
[[Clang_assert]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "57924a38968615e41f53e1bf78e3bf74616ee045"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "e9706541de090438acfc678a334b975d5e678057f76570bd2081ad7e5ed9a8da"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+0/Clang_assert.v12.0.1.armv6l-linux-musleabihf-cxx11.tar.gz"
[[Clang_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "eadf1f6a0114bb3947421d9332f872f11a22d026"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "384a28fe087844565f53c85f894abefa996709ead62ec049f6cae936d8e6c822"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+0/Clang_assert.v12.0.1.armv7l-linux-gnueabihf-cxx03.tar.gz"
[[Clang_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "43c4d2c50c75a90606657b5a8623e51cc5d11dff"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "e88c0e2eb4cdf7df0097175f23c73200752114642c9af499bc50c2d02eb39224"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+0/Clang_assert.v12.0.1.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[Clang_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx03"
git-tree-sha1 = "615f48b2440c3e6eae469af72fa79b47b698ca4e"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "def405be66c63a2912907b1187e10e302c6e7cf422a61d98e74a9f638e05124f"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+0/Clang_assert.v12.0.1.armv7l-linux-musleabihf-cxx03.tar.gz"
[[Clang_assert]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "781d400eb5b9ee196932e87c4ec1a7666892bc64"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "70834b19fbcfbbb3dbbe17cdc2bbae1da0b5da2bc60e7563c00fa05e35ca48a7"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+0/Clang_assert.v12.0.1.armv7l-linux-musleabihf-cxx11.tar.gz"
[[Clang_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "4cf362730e852d8b25eb493c698b233bc099d42d"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "d2592bce32b264b46bff1aef2975934d9816304f7ad07732073f5d6a7f21511f"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+0/Clang_assert.v12.0.1.i686-linux-gnu-cxx03.tar.gz"
[[Clang_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "84670f6b53daea6c1d31f5d46025b8ece436ec83"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "31f0d6f2d4b7a63652c0e8078661b9ecee1a45d86c3c1500f1528af69db9b655"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+0/Clang_assert.v12.0.1.i686-linux-gnu-cxx11.tar.gz"
[[Clang_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "73de4049d56db6dd2f34d71892ed57d079f9af6d"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "f4609a91a1f00132f792835125191accec94985c8d0ecc353aa55dd3850463f9"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+0/Clang_assert.v12.0.1.i686-linux-musl-cxx03.tar.gz"
[[Clang_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9e73a8d07faecf63f878f28e5b7818ceb0b37286"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "292e70b8c4d37d41f6a4707e5e7fba4e3c3bb252d861517cbeda8711b46eaf53"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+0/Clang_assert.v12.0.1.i686-linux-musl-cxx11.tar.gz"
[[Clang_assert]]
arch = "i686"
cxxstring_abi = "cxx03"
git-tree-sha1 = "70c1b3cdcadbcfdeabf6996c2839149b123dc380"
os = "windows"

    [[Clang_assert.download]]
    sha256 = "4f4d1747d20dcc0ace03d5e737bd227c0e2b1d8a8e81a945a06cb41830a70366"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+0/Clang_assert.v12.0.1.i686-w64-mingw32-cxx03.tar.gz"
[[Clang_assert]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6e2d106d89fc299b785126087bc295e415ecfc05"
os = "windows"

    [[Clang_assert.download]]
    sha256 = "8b5e85d5cf098a16257f72ab8c1ade7720077299a747564fe80d0cf573126fe6"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+0/Clang_assert.v12.0.1.i686-w64-mingw32-cxx11.tar.gz"
[[Clang_assert]]
arch = "powerpc64le"
cxxstring_abi = "cxx03"
git-tree-sha1 = "16d89ccc671072451296173d961dc8ee18f39ab9"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "5dabdf39cac5659ea5d9a8d9cef5dbeede06851483374407b1ef4bf06c6bc983"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+0/Clang_assert.v12.0.1.powerpc64le-linux-gnu-cxx03.tar.gz"
[[Clang_assert]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "45001e476f1a2efe1a71dc56623daf7d4b99a4ef"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "bb9e60c41fabcc9c60568978efa2eea7fa9fafc1cfe4870dd790f2e1b3ff961b"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+0/Clang_assert.v12.0.1.powerpc64le-linux-gnu-cxx11.tar.gz"
[[Clang_assert]]
arch = "x86_64"
git-tree-sha1 = "b3f046965969d739ef26bc40879e1e37d8112480"
os = "macos"

    [[Clang_assert.download]]
    sha256 = "90741c2544c71f53d9294a0bbe2186decfab6a1b705d3a65a5bd7f3fa285c06e"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+0/Clang_assert.v12.0.1.x86_64-apple-darwin.tar.gz"
[[Clang_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "e0a7b2800df187a54c2255342fee853b9ebc2cfa"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "1b29a92481d0d4bbad4aca03748bb4e0ddd33bf4a10a0f98e4f021eb88f6701e"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+0/Clang_assert.v12.0.1.x86_64-linux-gnu-cxx03.tar.gz"
[[Clang_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "c5ab3b74f03d5763be403f597c68f71ce76c6179"
libc = "glibc"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "4a4f223a19df788aef10fc8c0b2d009284db08151f4e1d6d4a5631f27d0a8508"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+0/Clang_assert.v12.0.1.x86_64-linux-gnu-cxx11.tar.gz"
[[Clang_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "1aa72fca8fc2f309a2aa233c7214e1ab772169d1"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "69b51a55e67a812b5e83e277eeff84f956f20234ce7d933d9cfd48bff4de6273"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+0/Clang_assert.v12.0.1.x86_64-linux-musl-cxx03.tar.gz"
[[Clang_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "3b931112f0fe88d28a1d561a3397ec96de6b3dab"
libc = "musl"
os = "linux"

    [[Clang_assert.download]]
    sha256 = "8b940f22c714caa26005f2ee934e4cebbf7e1e615eeb0e53d94da17603b7b5ea"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+0/Clang_assert.v12.0.1.x86_64-linux-musl-cxx11.tar.gz"
[[Clang_assert]]
arch = "x86_64"
git-tree-sha1 = "eb523a2ff0208b557e75176722e187897c2858f8"
os = "freebsd"

    [[Clang_assert.download]]
    sha256 = "ac5cd46cbcb59d0c06111acc6d28f58177a8cc1fb5a0e70c49d2ec86e19bcda5"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+0/Clang_assert.v12.0.1.x86_64-unknown-freebsd.tar.gz"
[[Clang_assert]]
arch = "x86_64"
cxxstring_abi = "cxx03"
git-tree-sha1 = "316b7ff26bdfb8a141be1d86e670be744088b3db"
os = "windows"

    [[Clang_assert.download]]
    sha256 = "6721832156e38046d07485ef73fa150a4b8398088773e9b85f2273d0649a62a4"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+0/Clang_assert.v12.0.1.x86_64-w64-mingw32-cxx03.tar.gz"
[[Clang_assert]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "89f822e52158246dd3cf13e27d8bcd9259cc2fd7"
os = "windows"

    [[Clang_assert.download]]
    sha256 = "445e59c670a10350a77bcc8d6761cd81c2f3f7e8b18852e73e2da5d24734fbe4"
    url = "https://github.com/JuliaBinaryWrappers/Clang_assert_jll.jl/releases/download/Clang_assert-v12.0.1+0/Clang_assert.v12.0.1.x86_64-w64-mingw32-cxx11.tar.gz"
